/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author Sebastian Moreno
 */
public class pantallaDevolucion extends javax.swing.JPanel {

    /**
     * Creates new form pantallaDevolucion
     */
    public pantallaDevolucion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPanelVentaEnCaja = new javax.swing.JLabel();
        txtBusquedaNombre1 = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        txtBusquedaNombre2 = new javax.swing.JLabel();
        inputNombre1 = new javax.swing.JTextField();
        txtBusquedaNombre3 = new javax.swing.JLabel();
        inputNombre2 = new javax.swing.JTextField();
        txtBusquedaNombre4 = new javax.swing.JLabel();
        inputNombre3 = new javax.swing.JTextField();
        txtBusquedaNombre5 = new javax.swing.JLabel();
        btnFinalizarVenta = new GUI.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnFinalizarVenta1 = new GUI.PanelRound();
        btnTxtFinalizarVenta1 = new javax.swing.JLabel();
        btnFinalizarVenta2 = new GUI.PanelRound();
        btnTxtFinalizarVenta2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPanelVentaEnCaja.setBackground(new java.awt.Color(0, 0, 0));
        txtPanelVentaEnCaja.setFont(new java.awt.Font("Product Sans Infanity", 0, 48)); // NOI18N
        txtPanelVentaEnCaja.setForeground(new java.awt.Color(0, 0, 0));
        txtPanelVentaEnCaja.setText("Devolución");
        add(txtPanelVentaEnCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 250, -1));

        txtBusquedaNombre1.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre1.setText("Venta:");
        add(txtBusquedaNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 150, 80, 30));

        inputNombre.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        inputNombre.setText("Nombre completo");
        inputNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNombreFocusLost(evt);
            }
        });
        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });
        inputNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNombreKeyTyped(evt);
            }
        });
        add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 570, 50));

        txtBusquedaNombre2.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre2.setText("Razon de la devolución.*:");
        add(txtBusquedaNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 280, 30));

        inputNombre1.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        inputNombre1.setText("Razon");
        inputNombre1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNombre1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNombre1FocusLost(evt);
            }
        });
        inputNombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputNombre1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNombre1KeyTyped(evt);
            }
        });
        add(inputNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 570, 50));

        txtBusquedaNombre3.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre3.setText("Productos devueltos.*:");
        add(txtBusquedaNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 280, 30));

        inputNombre2.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        inputNombre2.setText("Seleccionar productos");
        inputNombre2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNombre2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNombre2FocusLost(evt);
            }
        });
        inputNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombre2ActionPerformed(evt);
            }
        });
        inputNombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputNombre2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNombre2KeyTyped(evt);
            }
        });
        add(inputNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 570, 50));

        txtBusquedaNombre4.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre4.setText("Telefono.*:");
        add(txtBusquedaNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 280, 30));

        inputNombre3.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        inputNombre3.setText("Ingresar numero telefonico.");
        inputNombre3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNombre3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNombre3FocusLost(evt);
            }
        });
        inputNombre3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputNombre3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNombre3KeyTyped(evt);
            }
        });
        add(inputNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 570, 50));

        txtBusquedaNombre5.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre5.setText("Nombre Completo.*:");
        add(txtBusquedaNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 280, 30));

        btnFinalizarVenta.setBackground(new java.awt.Color(187, 187, 187));
        btnFinalizarVenta.setRoundBottomLeft(15);
        btnFinalizarVenta.setRoundBottomRight(15);
        btnFinalizarVenta.setRoundTopLeft(15);
        btnFinalizarVenta.setRoundTopRight(15);
        btnFinalizarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizarVentaMouseClicked(evt);
            }
        });
        btnFinalizarVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(187, 187, 187));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Productos", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnFinalizarVenta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 330));

        add(btnFinalizarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 300, 360));

        btnFinalizarVenta1.setBackground(new java.awt.Color(44, 44, 44));
        btnFinalizarVenta1.setRoundBottomLeft(15);
        btnFinalizarVenta1.setRoundBottomRight(15);
        btnFinalizarVenta1.setRoundTopLeft(15);
        btnFinalizarVenta1.setRoundTopRight(15);
        btnFinalizarVenta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizarVenta1MouseClicked(evt);
            }
        });
        btnFinalizarVenta1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTxtFinalizarVenta1.setFont(new java.awt.Font("Product Sans Infanity", 0, 36)); // NOI18N
        btnTxtFinalizarVenta1.setForeground(new java.awt.Color(255, 255, 255));
        btnTxtFinalizarVenta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTxtFinalizarVenta1.setText("Finalizar");
        btnTxtFinalizarVenta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinalizarVenta1.add(btnTxtFinalizarVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 290, 70));

        add(btnFinalizarVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, 370, 70));

        btnFinalizarVenta2.setBackground(new java.awt.Color(44, 44, 44));
        btnFinalizarVenta2.setRoundBottomLeft(15);
        btnFinalizarVenta2.setRoundBottomRight(15);
        btnFinalizarVenta2.setRoundTopLeft(15);
        btnFinalizarVenta2.setRoundTopRight(15);
        btnFinalizarVenta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizarVenta2MouseClicked(evt);
            }
        });
        btnFinalizarVenta2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTxtFinalizarVenta2.setFont(new java.awt.Font("Product Sans Infanity", 0, 36)); // NOI18N
        btnTxtFinalizarVenta2.setForeground(new java.awt.Color(255, 255, 255));
        btnTxtFinalizarVenta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTxtFinalizarVenta2.setText("Cancelar Devolucion");
        btnTxtFinalizarVenta2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinalizarVenta2.add(btnTxtFinalizarVenta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 350, 70));

        add(btnFinalizarVenta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, 370, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void inputNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombreFocusGained
        if (inputNombre.getText().equals("Nombre Producto")) {
            inputNombre.setText("");
        }
    }//GEN-LAST:event_inputNombreFocusGained

    private void inputNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombreFocusLost
        if (inputNombre.getText().trim().isEmpty()) {
            inputNombre.setText("Nombre Producto");
        }
    }//GEN-LAST:event_inputNombreFocusLost

    private void inputNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombreKeyReleased
      
    }//GEN-LAST:event_inputNombreKeyReleased

    private void inputNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombreKeyTyped
      
    }//GEN-LAST:event_inputNombreKeyTyped

    private void inputNombre1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombre1FocusGained
        if (inputNombre.getText().equals("Nombre Producto")) {
            inputNombre.setText("");
        }
    }//GEN-LAST:event_inputNombre1FocusGained

    private void inputNombre1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombre1FocusLost
        if (inputNombre.getText().trim().isEmpty()) {
            inputNombre.setText("Nombre Producto");
        }
    }//GEN-LAST:event_inputNombre1FocusLost

    private void inputNombre1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombre1KeyReleased
     
    }//GEN-LAST:event_inputNombre1KeyReleased

    private void inputNombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombre1KeyTyped
    
    }//GEN-LAST:event_inputNombre1KeyTyped

    private void inputNombre2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombre2FocusGained
        if (inputNombre.getText().equals("Nombre Producto")) {
            inputNombre.setText("");
        }
    }//GEN-LAST:event_inputNombre2FocusGained

    private void inputNombre2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombre2FocusLost
        if (inputNombre.getText().trim().isEmpty()) {
            inputNombre.setText("Nombre Producto");
        }
    }//GEN-LAST:event_inputNombre2FocusLost

    private void inputNombre2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombre2KeyReleased
      
    }//GEN-LAST:event_inputNombre2KeyReleased

    private void inputNombre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombre2KeyTyped
   
    }//GEN-LAST:event_inputNombre2KeyTyped

    private void inputNombre3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombre3FocusGained
        if (inputNombre.getText().equals("Nombre Producto")) {
            inputNombre.setText("");
        }
    }//GEN-LAST:event_inputNombre3FocusGained

    private void inputNombre3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombre3FocusLost
        if (inputNombre.getText().trim().isEmpty()) {
            inputNombre.setText("Nombre Producto");
        }
    }//GEN-LAST:event_inputNombre3FocusLost

    private void inputNombre3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombre3KeyReleased
 
    }//GEN-LAST:event_inputNombre3KeyReleased

    private void inputNombre3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombre3KeyTyped
      
    }//GEN-LAST:event_inputNombre3KeyTyped

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void inputNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre2ActionPerformed

    private void btnFinalizarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarVentaMouseClicked
      
    }//GEN-LAST:event_btnFinalizarVentaMouseClicked

    private void btnFinalizarVenta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarVenta1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarVenta1MouseClicked

    private void btnFinalizarVenta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarVenta2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarVenta2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.PanelRound btnFinalizarVenta;
    private GUI.PanelRound btnFinalizarVenta1;
    private GUI.PanelRound btnFinalizarVenta2;
    private javax.swing.JLabel btnTxtFinalizarVenta1;
    private javax.swing.JLabel btnTxtFinalizarVenta2;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputNombre1;
    private javax.swing.JTextField inputNombre2;
    private javax.swing.JTextField inputNombre3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtBusquedaNombre1;
    private javax.swing.JLabel txtBusquedaNombre2;
    private javax.swing.JLabel txtBusquedaNombre3;
    private javax.swing.JLabel txtBusquedaNombre4;
    private javax.swing.JLabel txtBusquedaNombre5;
    private javax.swing.JLabel txtPanelVentaEnCaja;
    // End of variables declaration//GEN-END:variables
}
