/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author Sebastian Moreno
 */
public class pantallaTicket extends javax.swing.JPanel {

    /**
     * Creates new form pantallaTicket
     */
    public pantallaTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPanelVentaEnCaja = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        txtBusquedaNombre1 = new javax.swing.JLabel();
        btnTarjeta = new GUI.PanelRound();
        btnTxtTarjeta = new javax.swing.JLabel();
        btnTarjeta1 = new GUI.PanelRound();
        btnTxtTarjeta1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPanelVentaEnCaja.setBackground(new java.awt.Color(0, 0, 0));
        txtPanelVentaEnCaja.setFont(new java.awt.Font("Product Sans Infanity", 0, 48)); // NOI18N
        txtPanelVentaEnCaja.setForeground(new java.awt.Color(0, 0, 0));
        txtPanelVentaEnCaja.setText("Ingresar el numero de ticket");
        add(txtPanelVentaEnCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 620, -1));

        inputNombre.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        inputNombre.setText("Numero");
        inputNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNombreFocusLost(evt);
            }
        });
        inputNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNombreKeyTyped(evt);
            }
        });
        add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 380, 50));

        txtBusquedaNombre1.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre1.setText("Numero de el ticket: ");
        add(txtBusquedaNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 280, 30));

        btnTarjeta.setBackground(new java.awt.Color(255, 44, 84));
        btnTarjeta.setRoundBottomLeft(15);
        btnTarjeta.setRoundBottomRight(15);
        btnTarjeta.setRoundTopLeft(15);
        btnTarjeta.setRoundTopRight(15);
        btnTarjeta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTxtTarjeta.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        btnTxtTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        btnTxtTarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTxtTarjeta.setText("CANCELAR");
        btnTxtTarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTxtTarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTxtTarjetaMouseClicked(evt);
            }
        });
        btnTarjeta.add(btnTxtTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 220, 50));

        add(btnTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 280, 50));

        btnTarjeta1.setBackground(new java.awt.Color(8, 124, 252));
        btnTarjeta1.setRoundBottomLeft(15);
        btnTarjeta1.setRoundBottomRight(15);
        btnTarjeta1.setRoundTopLeft(15);
        btnTarjeta1.setRoundTopRight(15);
        btnTarjeta1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTxtTarjeta1.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        btnTxtTarjeta1.setForeground(new java.awt.Color(255, 255, 255));
        btnTxtTarjeta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTxtTarjeta1.setText("INGRESAR");
        btnTxtTarjeta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTxtTarjeta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTxtTarjeta1MouseClicked(evt);
            }
        });
        btnTarjeta1.add(btnTxtTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 220, 50));

        add(btnTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 280, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void inputNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombreFocusGained
        if (inputNombre.getText().equals("Nombre Producto")) {
            inputNombre.setText("");
        }
    }//GEN-LAST:event_inputNombreFocusGained

    private void inputNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombreFocusLost
        if (inputNombre.getText().trim().isEmpty()) {
            inputNombre.setText("Nombre Producto");
        }
    }//GEN-LAST:event_inputNombreFocusLost

    private void inputNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombreKeyReleased
     
    }//GEN-LAST:event_inputNombreKeyReleased

    private void inputNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombreKeyTyped
       
    }//GEN-LAST:event_inputNombreKeyTyped

    private void btnTxtTarjetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTxtTarjetaMouseClicked
      
    }//GEN-LAST:event_btnTxtTarjetaMouseClicked

    private void btnTxtTarjeta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTxtTarjeta1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTxtTarjeta1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.PanelRound btnTarjeta;
    private GUI.PanelRound btnTarjeta1;
    private javax.swing.JLabel btnTxtTarjeta;
    private javax.swing.JLabel btnTxtTarjeta1;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JLabel txtBusquedaNombre1;
    private javax.swing.JLabel txtPanelVentaEnCaja;
    // End of variables declaration//GEN-END:variables
}
