package GUI.ModuloRegistrarSalida;

import DTOs.NuevaSalidaDTO;
import GUI.Aplicacion;
import javax.swing.text.AbstractDocument;
import DTOs.ProductoCargadoDTO;
import exception.SalidaException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author janot
 */
public class DialogoRegistrarSalida extends javax.swing.JDialog {
    private Aplicacion app;
    /**
     * Creates new form DialogoRegistrarSalida
     */
    public DialogoRegistrarSalida(java.awt.Frame parent, boolean modal, Aplicacion app) {
        super(parent, modal);
        initComponents();
        this.app = app;
        this.setLocationRelativeTo(null);
        buscadorProducto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSalida = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProductos = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMotivo = new javax.swing.JTextArea();
        jTextFieldProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        panelRound1 = new GUI.PanelRound();
        jLabelAgregar = new javax.swing.JLabel();
        panelRound2 = new GUI.PanelRound();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Product Sans Infanity", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Salida");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 450, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Product Sans Infanity", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Salida");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        jTextFieldSalida.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldSalida.setForeground(new java.awt.Color(0, 0, 0));
        ((AbstractDocument) jTextFieldSalida.getDocument()).setDocumentFilter(new SoloFiltroNumerico());
        jPanel1.add(jTextFieldSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 190, 30));

        jListProductos.setBackground(new java.awt.Color(255, 255, 255));
        jListProductos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListProductosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 280, 100));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Product Sans Infanity", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Buscar Producto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jTextAreaMotivo.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaMotivo.setColumns(15);
        jTextAreaMotivo.setRows(15);
        jScrollPane2.setViewportView(jTextAreaMotivo);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 190, 70));

        jTextFieldProducto.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldProducto.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProductoKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 190, 30));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Product Sans Infanity", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Motivo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        panelRound1.setBackground(new java.awt.Color(0, 0, 0));
        panelRound1.setRoundBottomLeft(10);
        panelRound1.setRoundBottomRight(10);
        panelRound1.setRoundTopLeft(10);
        panelRound1.setRoundTopRight(10);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAgregar.setText("Agregar");
        jLabelAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAgregarMouseClicked(evt);
            }
        });
        panelRound1.add(jLabelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 80, 30));

        panelRound2.setBackground(new java.awt.Color(0, 0, 0));
        panelRound2.setForeground(new java.awt.Color(0, 0, 0));
        panelRound2.setRoundBottomLeft(10);
        panelRound2.setRoundBottomRight(10);
        panelRound2.setRoundTopLeft(10);
        panelRound2.setRoundTopRight(10);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cancelar");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        panelRound2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jTextFieldProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductoKeyTyped
        Timer retrazoBuscador = new Timer(15, e ->{
            buscadorProducto();
        });
        retrazoBuscador.setRepeats(false);
        
        reiniciarTimer(retrazoBuscador);
        
    }//GEN-LAST:event_jTextFieldProductoKeyTyped

    private void jLabelAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarMouseClicked
        agregarNuevaSalida();
        app.reconstruirVentanaHistorialSalidas();
        
    }//GEN-LAST:event_jLabelAgregarMouseClicked

    private void jListProductosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListProductosValueChanged
        if (!(jListProductos.getSelectedValue() == null)) {
            jTextFieldProducto.setText(jListProductos.getSelectedValue().toString());
        }
    }//GEN-LAST:event_jListProductosValueChanged

    
    /////////////////////////////UTILS//////////////////////////////////////////////////////////////
    private void buscadorProducto(){
        String nombre = jTextFieldProducto.getText();
        List<ProductoCargadoDTO> listaProductos = new ArrayList<>();
        
        try {
            listaProductos = app.busquedaProductos(nombre);
        } catch (SalidaException e) {
            JOptionPane.showMessageDialog(this, e);
        }
        
        DefaultListModel<ProductoCargadoDTO> modelo = new DefaultListModel<>();
        jListProductos.setModel(modelo);
        
        for (ProductoCargadoDTO productoCargadoDTO : listaProductos) {
            modelo.addElement(productoCargadoDTO);
        }
    }
    
    private void agregarNuevaSalida(){
        ProductoCargadoDTO producto = jListProductos.getSelectedValue();
        String motivo = jTextAreaMotivo.getText();
        Double salida = null;

        Double stockAntes = null;
        Double stockDespues = null;
        
        String textoSalida = jTextFieldSalida.getText().trim();

        if (textoSalida.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo de salida no puede estar vacío.");
            return;
        }

        try {
            salida = Double.parseDouble(textoSalida);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un número válido en el campo de salida.");
            return;
        }
        
        if(producto != null){
            stockAntes = producto.getStock();
            stockDespues = producto.getStock() - salida;
        }
        
        try {
            if(app.agregarNuevaSalida(new NuevaSalidaDTO(producto, motivo, stockAntes, salida, stockDespues))){
                app.restarStockAProducto(salida, producto.getCodigo());
                dispose();
            }
        } catch (SalidaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void reiniciarTimer(Timer retrazoBuscador) {
        retrazoBuscador.restart(); // reinicia el contador desde cero
    }

    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAgregar;
    private javax.swing.JList<ProductoCargadoDTO> jListProductos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaMotivo;
    private javax.swing.JTextField jTextFieldProducto;
    private javax.swing.JTextField jTextFieldSalida;
    private GUI.PanelRound panelRound1;
    private GUI.PanelRound panelRound2;
    // End of variables declaration//GEN-END:variables
}
