package GUI.ModuloRegistrarSalida;

import DTOs.SalidaDTO;
import GUI.Aplicacion;
import exception.SalidaException;
import java.text.SimpleDateFormat;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author janot
 */
public class VentanaHistorialSalidas extends javax.swing.JPanel {

    //Control de aplicacion
    private Aplicacion app;

    /**
     * Creates new form ventanaHistorialSalidas
     */
    public VentanaHistorialSalidas(Aplicacion app) {
        initComponents();
        this.app = app;
        //Carga todas las salidas en la tabla
        cargarSalidasTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSalidas = new javax.swing.JTable();
        btnAtras = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelIconAgregarSalida = new javax.swing.JLabel();
        jLabelFechaHasta = new javax.swing.JLabel();
        jLabelAgregarSalida = new javax.swing.JLabel();
        jLabelProducto = new javax.swing.JLabel();
        jLabelFechaDesde = new javax.swing.JLabel();
        datePickerHasta = new com.github.lgooddatepicker.components.DatePicker();
        jTextFieldProducto = new javax.swing.JTextField();
        datePickerDesde = new com.github.lgooddatepicker.components.DatePicker();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableSalidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Fecha", "Producto", "Motivo", "Stock Antes", "Salida", "Stock Despues"
            }
        ));
        jScrollPane1.setViewportView(jTableSalidas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 1080, -1));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras (1).png"))); // NOI18N
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Historial De Salidas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 440, -1));

        jLabelIconAgregarSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar (1).png"))); // NOI18N
        jLabelIconAgregarSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIconAgregarSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconAgregarSalidaMouseClicked(evt);
            }
        });
        add(jLabelIconAgregarSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, -1, -1));

        jLabelFechaHasta.setBackground(new java.awt.Color(0, 0, 0));
        jLabelFechaHasta.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        jLabelFechaHasta.setText("Fecha Hasta:");
        jLabelFechaHasta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelFechaHasta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFechaHastaMouseClicked(evt);
            }
        });
        add(jLabelFechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, 140, 60));

        jLabelAgregarSalida.setBackground(new java.awt.Color(0, 0, 0));
        jLabelAgregarSalida.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        jLabelAgregarSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAgregarSalida.setText("Agregar Salida");
        jLabelAgregarSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAgregarSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAgregarSalidaMouseClicked(evt);
            }
        });
        add(jLabelAgregarSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 530, 140, 60));

        jLabelProducto.setBackground(new java.awt.Color(0, 0, 0));
        jLabelProducto.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        jLabelProducto.setText("Producto:");
        jLabelProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProductoMouseClicked(evt);
            }
        });
        add(jLabelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 140, 60));

        jLabelFechaDesde.setBackground(new java.awt.Color(0, 0, 0));
        jLabelFechaDesde.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        jLabelFechaDesde.setText("Fecha Desde:");
        jLabelFechaDesde.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelFechaDesde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFechaDesdeMouseClicked(evt);
            }
        });
        add(jLabelFechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 140, 60));

        datePickerHasta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datePickerHastaPropertyChange(evt);
            }
        });
        datePickerHasta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                datePickerHastaKeyTyped(evt);
            }
        });
        add(datePickerHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, 190, 30));

        jTextFieldProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProductoKeyTyped(evt);
            }
        });
        add(jTextFieldProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 180, 30));

        datePickerDesde.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datePickerDesdePropertyChange(evt);
            }
        });
        datePickerDesde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                datePickerDesdeKeyTyped(evt);
            }
        });
        add(datePickerDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 190, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        app.mostrarVentanaOpcionesInventario();
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void jLabelFechaHastaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFechaHastaMouseClicked
        app.mostrarDialogoAgregarSalida();
    }//GEN-LAST:event_jLabelFechaHastaMouseClicked

    private void jLabelIconAgregarSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconAgregarSalidaMouseClicked
        app.mostrarDialogoAgregarSalida();
    }//GEN-LAST:event_jLabelIconAgregarSalidaMouseClicked

    private void jLabelAgregarSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarSalidaMouseClicked
        app.mostrarDialogoAgregarSalida();


    }//GEN-LAST:event_jLabelAgregarSalidaMouseClicked

    private void jLabelProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelProductoMouseClicked

    private void jLabelFechaDesdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFechaDesdeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFechaDesdeMouseClicked

    private void jTextFieldProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductoKeyTyped
        //Generea un retrazo de 15 mili al momento de realizar un filtro
        Timer retrazoBuscador = new Timer(15, e -> {
            cargarSalidasFiltradasTabla();
        });
        retrazoBuscador.setRepeats(false);

        reiniciarTimer(retrazoBuscador);
    }//GEN-LAST:event_jTextFieldProductoKeyTyped

    private void datePickerDesdeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datePickerDesdeKeyTyped
        cargarSalidasFiltradasTabla();
    }//GEN-LAST:event_datePickerDesdeKeyTyped

    private void datePickerHastaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datePickerHastaKeyTyped

    }//GEN-LAST:event_datePickerHastaKeyTyped

    private void datePickerDesdePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datePickerDesdePropertyChange
        cargarSalidasFiltradasTabla();
    }//GEN-LAST:event_datePickerDesdePropertyChange

    private void datePickerHastaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datePickerHastaPropertyChange
        cargarSalidasFiltradasTabla();
    }//GEN-LAST:event_datePickerHastaPropertyChange

    /////////////////////////////UTILS//////////////////////////////////////////////////////////////
    //Carga todas las salidas de la tabla
    private void cargarSalidasTabla() {
        List<SalidaDTO> listaSalida = new ArrayList<>();

        try {
            listaSalida = app.cargarSalidas();
        } catch (SalidaException e) {
            JOptionPane.showMessageDialog(this, e);
        }

        DefaultTableModel model = (DefaultTableModel) jTableSalidas.getModel();
        model.setRowCount(0);
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy HH:mm");
      
        for (SalidaDTO salidaDTO : listaSalida) {
            model.addRow(new Object[]{
                format.format(salidaDTO.getFecha()),
                salidaDTO.getProducto().getNombre(),
                salidaDTO.getMotivo(),
                salidaDTO.getStockAntes(),
                salidaDTO.getCantidadSalida(),
                salidaDTO.getStockDespues()
            });
        }
        jTableSalidas.setModel(model);
    }

    //Carga las salidas en la tabla segun se van haciendo los filtroa
    public void cargarSalidasFiltradasTabla() {
        String nombre = jTextFieldProducto.getText();
        Date fechaDesde = null;
        Date fechaHasta = null;

        if (datePickerDesde.getDate() != null) {
            fechaDesde = Date.from(datePickerDesde.getDate().atStartOfDay(ZoneId.systemDefault()).toInstant());
        }

        if (datePickerHasta.getDate() != null) {
            fechaHasta = Date.from(datePickerHasta.getDate().atStartOfDay(ZoneId.systemDefault()).toInstant());
        }

        List<SalidaDTO> listaSalida = new ArrayList<>();

        try {

            listaSalida = app.cargarSalidasFiltradas(nombre, fechaDesde, fechaHasta);

        } catch (SalidaException e) {
            JOptionPane.showMessageDialog(this, e);
        }

        DefaultTableModel model = (DefaultTableModel) jTableSalidas.getModel();
        model.setRowCount(0);
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        
        for (SalidaDTO salidaDTO : listaSalida) {
            model.addRow(new Object[]{
                format.format(salidaDTO.getFecha()),
                salidaDTO.getProducto().getNombre(),
                salidaDTO.getMotivo(),
                salidaDTO.getStockAntes(),
                salidaDTO.getCantidadSalida(),
                salidaDTO.getStockDespues()
            });
        }
        jTableSalidas.setModel(model);
    }

    //Sirve para reiniciar el timer cada vez que se hace la consulta
    private void reiniciarTimer(Timer retrazoBuscador) {
        retrazoBuscador.restart(); // reinicia el contador desde cero
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAtras;
    private com.github.lgooddatepicker.components.DatePicker datePickerDesde;
    private com.github.lgooddatepicker.components.DatePicker datePickerHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAgregarSalida;
    private javax.swing.JLabel jLabelFechaDesde;
    private javax.swing.JLabel jLabelFechaHasta;
    private javax.swing.JLabel jLabelIconAgregarSalida;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSalidas;
    private javax.swing.JTextField jTextFieldProducto;
    // End of variables declaration//GEN-END:variables
}
