/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ModuloRealizarDevolucion;

/**
 *
 * @author Lap-064
 */
public class PantallaHistorialDevoluciones extends javax.swing.JPanel {

    /**
     * Creates new form pantallaHistorialDevoluciones
     */
    public PantallaHistorialDevoluciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFinalizarVenta = new GUI.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        inputNombre = new javax.swing.JTextField();
        inputNombre1 = new javax.swing.JTextField();
        inputNombre2 = new javax.swing.JTextField();
        inputNombre3 = new javax.swing.JTextField();
        txtBusquedaNombre1 = new javax.swing.JLabel();
        txtBusquedaNombre2 = new javax.swing.JLabel();
        txtBusquedaNombre3 = new javax.swing.JLabel();
        txtBusquedaNombre4 = new javax.swing.JLabel();
        txtPanelVentaEnCaja = new javax.swing.JLabel();
        btnTarjeta1 = new GUI.PanelRound();
        btnTxtTarjeta1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFinalizarVenta.setBackground(new java.awt.Color(187, 187, 187));
        btnFinalizarVenta.setRoundBottomLeft(15);
        btnFinalizarVenta.setRoundBottomRight(15);
        btnFinalizarVenta.setRoundTopLeft(15);
        btnFinalizarVenta.setRoundTopRight(15);
        btnFinalizarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizarVentaMouseClicked(evt);
            }
        });
        btnFinalizarVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(187, 187, 187));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo reembolso", "Articulos Reembolsados", "Razon", "Fecha", "ID", "Cliente", "Total Regresado", "Detalles"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnFinalizarVenta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 990, 330));

        add(btnFinalizarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 1010, 360));

        inputNombre.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        inputNombre.setText("Seleccionar Fecha");
        inputNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNombreFocusLost(evt);
            }
        });
        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });
        inputNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNombreKeyTyped(evt);
            }
        });
        add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 270, 50));

        inputNombre1.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        inputNombre1.setText("Telefono");
        inputNombre1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNombre1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNombre1FocusLost(evt);
            }
        });
        inputNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombre1ActionPerformed(evt);
            }
        });
        inputNombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputNombre1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNombre1KeyTyped(evt);
            }
        });
        add(inputNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 240, 50));

        inputNombre2.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        inputNombre2.setText("Nombre");
        inputNombre2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNombre2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNombre2FocusLost(evt);
            }
        });
        inputNombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputNombre2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNombre2KeyTyped(evt);
            }
        });
        add(inputNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 270, 50));

        inputNombre3.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        inputNombre3.setText("Seleccionar Fecha");
        inputNombre3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNombre3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNombre3FocusLost(evt);
            }
        });
        inputNombre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombre3ActionPerformed(evt);
            }
        });
        inputNombre3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputNombre3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNombre3KeyTyped(evt);
            }
        });
        add(inputNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 270, 50));

        txtBusquedaNombre1.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre1.setText("Fecha Fin:");
        add(txtBusquedaNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 230, 30));

        txtBusquedaNombre2.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre2.setText("Telefono cliente : ");
        add(txtBusquedaNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 230, 30));

        txtBusquedaNombre3.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre3.setText("Nombre Cliente :");
        add(txtBusquedaNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 230, 30));

        txtBusquedaNombre4.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre4.setText("Fecha Inicio:");
        add(txtBusquedaNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 230, 30));

        txtPanelVentaEnCaja.setBackground(new java.awt.Color(0, 0, 0));
        txtPanelVentaEnCaja.setFont(new java.awt.Font("Product Sans Infanity", 0, 48)); // NOI18N
        txtPanelVentaEnCaja.setText("Historial de Devoluciones");
        add(txtPanelVentaEnCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 540, -1));

        btnTarjeta1.setBackground(new java.awt.Color(8, 124, 252));
        btnTarjeta1.setRoundBottomLeft(15);
        btnTarjeta1.setRoundBottomRight(15);
        btnTarjeta1.setRoundTopLeft(15);
        btnTarjeta1.setRoundTopRight(15);
        btnTarjeta1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTxtTarjeta1.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        btnTxtTarjeta1.setForeground(new java.awt.Color(255, 255, 255));
        btnTxtTarjeta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTxtTarjeta1.setText("INGRESAR");
        btnTxtTarjeta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTxtTarjeta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTxtTarjeta1MouseClicked(evt);
            }
        });
        btnTarjeta1.add(btnTxtTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 400, 40));

        add(btnTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 460, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarVentaMouseClicked

    }//GEN-LAST:event_btnFinalizarVentaMouseClicked

    private void inputNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombreFocusGained
        if (inputNombre.getText().equals("Nombre Producto")) {
            inputNombre.setText("");
        }
    }//GEN-LAST:event_inputNombreFocusGained

    private void inputNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombreFocusLost
        if (inputNombre.getText().trim().isEmpty()) {
            inputNombre.setText("Nombre Producto");
        }
    }//GEN-LAST:event_inputNombreFocusLost

    private void inputNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombreKeyReleased

    }//GEN-LAST:event_inputNombreKeyReleased

    private void inputNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombreKeyTyped

    }//GEN-LAST:event_inputNombreKeyTyped

    private void inputNombre1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombre1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre1FocusGained

    private void inputNombre1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombre1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre1FocusLost

    private void inputNombre1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombre1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre1KeyReleased

    private void inputNombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombre1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre1KeyTyped

    private void inputNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre1ActionPerformed

    private void inputNombre2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombre2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre2FocusGained

    private void inputNombre2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombre2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre2FocusLost

    private void inputNombre2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombre2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre2KeyReleased

    private void inputNombre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombre2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre2KeyTyped

    private void inputNombre3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombre3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre3FocusGained

    private void inputNombre3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombre3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre3FocusLost

    private void inputNombre3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombre3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre3KeyReleased

    private void inputNombre3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombre3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre3KeyTyped

    private void inputNombre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombre3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre3ActionPerformed

    private void btnTxtTarjeta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTxtTarjeta1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTxtTarjeta1MouseClicked

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.PanelRound btnFinalizarVenta;
    private GUI.PanelRound btnTarjeta1;
    private javax.swing.JLabel btnTxtTarjeta1;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputNombre1;
    private javax.swing.JTextField inputNombre2;
    private javax.swing.JTextField inputNombre3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtBusquedaNombre1;
    private javax.swing.JLabel txtBusquedaNombre2;
    private javax.swing.JLabel txtBusquedaNombre3;
    private javax.swing.JLabel txtBusquedaNombre4;
    private javax.swing.JLabel txtPanelVentaEnCaja;
    // End of variables declaration//GEN-END:variables
}
