/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ModuloRealizarDevolucion;

import GUI.Aplicacion;
import java.awt.Color;

/**
 *
 * @author Sebastian Moreno
 */
public class PantallaMenuDevolucion extends javax.swing.JPanel {

    /**
     * Creates new form pantallaMenuDevolucion
     */
    private Aplicacion app;
    public PantallaMenuDevolucion(Aplicacion app) {
        this.app = app;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPanelVentaEnCaja = new javax.swing.JLabel();
        pnlBotonVentaEnCaja = new javax.swing.JPanel();
        txtBusquedaNombre2 = new javax.swing.JLabel();
        pnlBotonVentaEnCaja1 = new javax.swing.JPanel();
        icnRealizarVenta1 = new javax.swing.JLabel();
        txtBusquedaNombre1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPanelVentaEnCaja.setBackground(new java.awt.Color(0, 0, 0));
        txtPanelVentaEnCaja.setFont(new java.awt.Font("Product Sans Infanity", 0, 48)); // NOI18N
        txtPanelVentaEnCaja.setText("Area de Devolución");
        add(txtPanelVentaEnCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 420, -1));

        pnlBotonVentaEnCaja.setBackground(new java.awt.Color(73, 69, 79));
        pnlBotonVentaEnCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBotonVentaEnCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBotonVentaEnCajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBotonVentaEnCajaMouseExited(evt);
            }
        });
        pnlBotonVentaEnCaja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusquedaNombre2.setFont(new java.awt.Font("Product Sans Infanity", 0, 36)); // NOI18N
        txtBusquedaNombre2.setForeground(new java.awt.Color(255, 255, 255));
        txtBusquedaNombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBusquedaNombre2.setText("Realizar una Devolución");
        pnlBotonVentaEnCaja.add(txtBusquedaNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 70));

        add(pnlBotonVentaEnCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 440, 70));

        pnlBotonVentaEnCaja1.setBackground(new java.awt.Color(73, 69, 79));
        pnlBotonVentaEnCaja1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBotonVentaEnCaja1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBotonVentaEnCaja1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBotonVentaEnCaja1MouseExited(evt);
            }
        });
        pnlBotonVentaEnCaja1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icnRealizarVenta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icnRealizarVenta1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icnRealizarVenta1MouseEntered(evt);
            }
        });
        pnlBotonVentaEnCaja1.add(icnRealizarVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 130, 150));

        txtBusquedaNombre1.setFont(new java.awt.Font("Product Sans Infanity", 0, 36)); // NOI18N
        txtBusquedaNombre1.setForeground(new java.awt.Color(255, 255, 255));
        txtBusquedaNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBusquedaNombre1.setText("Historial de Devoluciones");
        pnlBotonVentaEnCaja1.add(txtBusquedaNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 70));

        add(pnlBotonVentaEnCaja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 440, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlBotonVentaEnCajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBotonVentaEnCajaMouseEntered
        // TODO add your handling code here:
        pnlBotonVentaEnCaja.setBackground(new Color(100, 100, 120, 180));
    }//GEN-LAST:event_pnlBotonVentaEnCajaMouseEntered

    private void pnlBotonVentaEnCajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBotonVentaEnCajaMouseExited
        // TODO add your handling code here:
        pnlBotonVentaEnCaja.setBackground(new Color(73, 69, 79, 150));
    }//GEN-LAST:event_pnlBotonVentaEnCajaMouseExited

    private void icnRealizarVenta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icnRealizarVenta1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_icnRealizarVenta1MouseClicked

    private void icnRealizarVenta1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icnRealizarVenta1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_icnRealizarVenta1MouseEntered

    private void pnlBotonVentaEnCaja1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBotonVentaEnCaja1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlBotonVentaEnCaja1MouseEntered

    private void pnlBotonVentaEnCaja1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBotonVentaEnCaja1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlBotonVentaEnCaja1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icnRealizarVenta1;
    private javax.swing.JPanel pnlBotonVentaEnCaja;
    private javax.swing.JPanel pnlBotonVentaEnCaja1;
    private javax.swing.JLabel txtBusquedaNombre1;
    private javax.swing.JLabel txtBusquedaNombre2;
    private javax.swing.JLabel txtPanelVentaEnCaja;
    // End of variables declaration//GEN-END:variables
}
