/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ModuloRealizarDevolucion;

/**
 *
 * @author Lap-064
 */
public class PantallaDetallesHistorialDevolucion extends javax.swing.JPanel {

    /**
     * Creates new form pantallaDetallesHistorialDevolucion
     */
    public PantallaDetallesHistorialDevolucion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPanelVentaEnCaja = new javax.swing.JLabel();
        txtBusquedaNombre2 = new javax.swing.JLabel();
        txtBusquedaNombre3 = new javax.swing.JLabel();
        btnFinalizarVenta = new GUI.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtBusquedaNombre4 = new javax.swing.JLabel();
        txtBusquedaNombre5 = new javax.swing.JLabel();
        txtBusquedaNombre6 = new javax.swing.JLabel();
        txtBusquedaNombre7 = new javax.swing.JLabel();
        txtBusquedaNombre8 = new javax.swing.JLabel();
        txtBusquedaNombre9 = new javax.swing.JLabel();
        txtBusquedaNombre10 = new javax.swing.JLabel();
        txtBusquedaNombre11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPanelVentaEnCaja.setBackground(new java.awt.Color(0, 0, 0));
        txtPanelVentaEnCaja.setFont(new java.awt.Font("Product Sans Infanity", 0, 48)); // NOI18N
        txtPanelVentaEnCaja.setText("Detalles Devolucion");
        add(txtPanelVentaEnCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 430, -1));

        txtBusquedaNombre2.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre2.setText("Motivo:");
        add(txtBusquedaNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 400, 30));

        txtBusquedaNombre3.setFont(new java.awt.Font("Product Sans Infanity", 1, 26)); // NOI18N
        txtBusquedaNombre3.setText("Venta ");
        add(txtBusquedaNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 100, 30));

        btnFinalizarVenta.setBackground(new java.awt.Color(187, 187, 187));
        btnFinalizarVenta.setRoundBottomLeft(15);
        btnFinalizarVenta.setRoundBottomRight(15);
        btnFinalizarVenta.setRoundTopLeft(15);
        btnFinalizarVenta.setRoundTopRight(15);
        btnFinalizarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizarVentaMouseClicked(evt);
            }
        });
        btnFinalizarVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(187, 187, 187));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Productos", "Cantidad", "Precio Unitario", "Importe"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnFinalizarVenta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 410));

        add(btnFinalizarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 650, 410));

        txtBusquedaNombre4.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre4.setText("Devolucion : ");
        add(txtBusquedaNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, 30));

        txtBusquedaNombre5.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre5.setText("Fecha Compra : ");
        add(txtBusquedaNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 270, 30));

        txtBusquedaNombre6.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre6.setText("Metodo Pago :  ");
        add(txtBusquedaNombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 270, 30));

        txtBusquedaNombre7.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre7.setText("Cajero:");
        add(txtBusquedaNombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 270, 30));

        txtBusquedaNombre8.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre8.setText("Cajero:");
        add(txtBusquedaNombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 270, 30));

        txtBusquedaNombre9.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre9.setText("Cliente:");
        add(txtBusquedaNombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 270, 30));

        txtBusquedaNombre10.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre10.setText("Fecha devolucion:");
        add(txtBusquedaNombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 400, 30));

        txtBusquedaNombre11.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre11.setText("Monto devolucion:");
        add(txtBusquedaNombre11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 400, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarVentaMouseClicked

    }//GEN-LAST:event_btnFinalizarVentaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.PanelRound btnFinalizarVenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtBusquedaNombre10;
    private javax.swing.JLabel txtBusquedaNombre11;
    private javax.swing.JLabel txtBusquedaNombre2;
    private javax.swing.JLabel txtBusquedaNombre3;
    private javax.swing.JLabel txtBusquedaNombre4;
    private javax.swing.JLabel txtBusquedaNombre5;
    private javax.swing.JLabel txtBusquedaNombre6;
    private javax.swing.JLabel txtBusquedaNombre7;
    private javax.swing.JLabel txtBusquedaNombre8;
    private javax.swing.JLabel txtBusquedaNombre9;
    private javax.swing.JLabel txtPanelVentaEnCaja;
    // End of variables declaration//GEN-END:variables
}
