/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.ModuloRegistrarEntrada;

import Exception.InventarioException;
import GUI.Aplicacion;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HP
 */
public class DatosProductoEntrada extends javax.swing.JDialog {
    private Aplicacion control;
    private double PrecioCompra, Unidades;
    /**
     * Creates new form DatosProductoEntrada
     * @param parent
     */
    public DatosProductoEntrada(Aplicacion control) {       
        initComponents();
        this.control = control;
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        labelStock = new javax.swing.JLabel();
        CampoPrecioCompra = new javax.swing.JTextField();
        CampoStock = new javax.swing.JTextField();
        BtnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Datos del Producto de Entrada");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        labelPrecio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelPrecio.setText("Precio de compra");
        getContentPane().add(labelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        labelStock.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelStock.setText("Stock");
        getContentPane().add(labelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));
        getContentPane().add(CampoPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 190, 30));
        getContentPane().add(CampoStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 190, 30));

        BtnAceptar.setBackground(new java.awt.Color(0, 0, 0));
        BtnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAceptar.setText("Aceptar");
        BtnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAceptarMouseClicked(evt);
            }
        });
        getContentPane().add(BtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAceptarMouseClicked
        // TODO add your handling code here  
        try {          
            validarCampos();
            control.agregarProductoEntrada(); 
            control.mostrarVentanaInformacionEntrada();
            dispose();
        } catch (InventarioException ex) {
            control.MostrarErrorNumeroInvalido();
        }      
    }//GEN-LAST:event_BtnAceptarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JTextField CampoPrecioCompra;
    private javax.swing.JTextField CampoStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelStock;
    // End of variables declaration//GEN-END:variables

public void validarCampos() throws InventarioException {
    
    String textoUnidades = CampoStock.getText().trim();
    String textoPrecio = CampoPrecioCompra.getText().trim();
    try {        
        //  textoPrecio = textoPrecio.replace(",", ".").trim(); 
          PrecioCompra = Double.parseDouble(textoPrecio);
          if (PrecioCompra <= 0) {
              throw new InventarioException("Precio de compra inválido.");
          }
      } catch (NumberFormatException e) {

          throw new InventarioException("Formato inválido en precio de compra.");
      }
      try {
          textoUnidades = textoUnidades.replace(",", ".");
          Unidades = Double.parseDouble(textoUnidades);
          if (Unidades <= 0) {
              throw new InventarioException("Cantidad de unidades inválida.");
          }
      } catch (NumberFormatException e) {
          throw new InventarioException("Formato inválido en unidades.");
      }
      ObtenerPrecioCompra(PrecioCompra);
      ObtenerUnidades(Unidades);
    }

    
    public void ObtenerUnidades(double Unidades){
       control.setUnidades(Unidades);
    }
    public void ObtenerPrecioCompra(double PrecioCompra){
        control.setPrecioCompra(PrecioCompra);
    }
}
