 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.ModuloRegistrarEntrada;

import Exception.InventarioException;
import GUI.Aplicacion;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HP
 */
public class FormularioDatosEntrada extends javax.swing.JDialog {
    private Aplicacion control;
    private Boolean cancelar;
    private double PrecioCompra, Unidades;
    /**
     * Creates new form VentanaDatosEntrada
     */
    public FormularioDatosEntrada(Aplicacion control) {
        this.control = control;
        this.cancelar = false;
        initComponents();
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitulo = new javax.swing.JLabel();
        LabelUnidades = new javax.swing.JLabel();
        LabelPrecioCompra = new javax.swing.JLabel();
        campoUnidades = new javax.swing.JTextField();
        campoPrecioCompra = new javax.swing.JTextField();
        BotonAceptar = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LabelTitulo.setText("Datos del producto");

        LabelUnidades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelUnidades.setText("Unidades: ");

        LabelPrecioCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelPrecioCompra.setText("Precio de compra: ");

        campoUnidades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoUnidades.setPreferredSize(new java.awt.Dimension(150, 31));

        campoPrecioCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoPrecioCompra.setPreferredSize(new java.awt.Dimension(150, 31));

        BotonAceptar.setBackground(new java.awt.Color(0, 0, 0));
        BotonAceptar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        BotonAceptar.setText("Aceptar");
        BotonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAceptarMouseClicked(evt);
            }
        });

        BotonCancelar.setBackground(new java.awt.Color(204, 204, 204));
        BotonCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonCancelar.setText("Cancelar");
        BotonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelPrecioCompra)
                        .addGap(18, 18, 18)
                        .addComponent(campoPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelUnidades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelTitulo)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotonAceptar)
                        .addGap(59, 59, 59)
                        .addComponent(BotonCancelar)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LabelTitulo)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelUnidades)
                    .addComponent(campoUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPrecioCompra)
                    .addComponent(campoPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAceptar)
                    .addComponent(BotonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCancelarMouseClicked
        // TODO add your handling code here:
       if(evt.getClickCount() == 1){
            cancelar = true;
            control.MostrarErrorUsarioCancelo();
            dispose();
        }
    }//GEN-LAST:event_BotonCancelarMouseClicked

    private void BotonAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAceptarMouseClicked
        // TODO add your handling code here:
        try {
            validarPrecioCompra();
            ObtenerPrecioCompra(PrecioCompra);
            ObtenerUnidades(Unidades);
            control.agregarProductoEntrada(); 
            control.mostrarVentanaInformacionEntrada();
            dispose();
        } catch (InventarioException ex) {
            Logger.getLogger(FormularioDatosEntrada.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_BotonAceptarMouseClicked
   
    public void validarPrecioCompra() throws InventarioException{
        String Tunidades = campoUnidades.getText().trim();
        String TPrecioCompra = campoPrecioCompra.getText().trim();

        try {
           PrecioCompra = Double.parseDouble(TPrecioCompra);
           if (PrecioCompra <= 0) {
               control.MostrarErrorNumeroInvalido(); // o un método más específico
               campoPrecioCompra.requestFocus();
               throw new InventarioException("Precio de compra inválido.");
           }
       } catch (NumberFormatException e) {
           control.MostrarErrorNumeroInvalido();
           campoPrecioCompra.requestFocus();
           throw new InventarioException("Formato inválido en precio de compra.");
       }

       try {
           Unidades = Double.parseDouble(Tunidades);
           if (Unidades <= 0) {
               control.MostrarErrorNumeroInvalido();
               campoUnidades.requestFocus();
               throw new InventarioException("Cantidad de unidades inválida.");
           }
       } catch (NumberFormatException e) {
           control.MostrarErrorNumeroInvalido();
           campoUnidades.requestFocus();
           throw new InventarioException("Formato inválido en unidades.");
       }
        
    }
    
    public void ObtenerUnidades(double Unidades){
       control.setUnidades(Unidades);
    }
    public void ObtenerPrecioCompra(double PrecioCompra){
        control.setPrecioCompra(PrecioCompra);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JLabel LabelPrecioCompra;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel LabelUnidades;
    private javax.swing.JTextField campoPrecioCompra;
    private javax.swing.JTextField campoUnidades;
    // End of variables declaration//GEN-END:variables

}
