/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ModuloRegistrarEntrada;

import DTOs.ProductoCargadoDTO;
import Exception.NegocioException;
import GUI.Aplicacion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class FormularioProductoNuevo extends javax.swing.JPanel {
    private Aplicacion control;
    private ProductoCargadoDTO productoNuevo;
    /**
     * Creates new form FormularioProductoNuevo
     */
    public FormularioProductoNuevo(Aplicacion control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelCategoria = new javax.swing.JLabel();
        labelPesable = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        campoPesable = new javax.swing.JComboBox<>();
        campoPrecioUnidad = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoCategoria = new javax.swing.JTextField();
        campoDescripcion = new javax.swing.JTextField();
        BtnCancelar = new javax.swing.JButton();
        BtnAceptar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Registro de Producto Nuevo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Datos del producto");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        labelPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPrecio.setText("Precio unidad:");
        add(labelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        labelNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNombre.setText("Nombre:");
        add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        labelCategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCategoria.setText("Categoria:");
        add(labelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        labelPesable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPesable.setText("¿Es pesable?");
        add(labelPesable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        labelDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelDescripcion.setText("Descripcion");
        add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        campoPesable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "default", "Si", "No" }));
        add(campoPesable, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        campoPrecioUnidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoPrecioUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 390, 170, -1));

        campoNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNombre.setToolTipText("");
        add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 170, -1));

        campoCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 170, -1));

        campoDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 170, -1));

        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseClicked(evt);
            }
        });
        add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, -1));

        BtnAceptar.setBackground(new java.awt.Color(0, 0, 0));
        BtnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAceptar.setText("Aceptar");
        BtnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAceptarMouseClicked(evt);
            }
        });
        add(BtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAceptarMouseClicked
        // TODO add your handling code here:
        validaciones();
        try {
            control.agregarProductoNuevo(productoNuevo);
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e);
        }
        
        try {
            control.mostrarVentanaSeleccionarProductosEntrada();
        } catch (NegocioException ex) {
            Logger.getLogger(FormularioProductoNuevo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAceptarMouseClicked

    private void BtnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseClicked
        try {
            // TODO add your handling code here:
            control.mostrarVentanaSeleccionarProductosEntrada();
        } catch (NegocioException ex) {
            Logger.getLogger(FormularioProductoNuevo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnCancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JTextField campoCategoria;
    private javax.swing.JTextField campoDescripcion;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JComboBox<String> campoPesable;
    private javax.swing.JTextField campoPrecioUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPesable;
    private javax.swing.JLabel labelPrecio;
    // End of variables declaration//GEN-END:variables


 public ProductoCargadoDTO crearProductoNuevo(String nombre, String descripcion, String categoria, double precio, Boolean esPesable){
        productoNuevo = new ProductoCargadoDTO();
        productoNuevo.setCategoria(categoria);
        productoNuevo.setDescripcion(descripcion);
        productoNuevo.setEsPesable(esPesable);
        productoNuevo.setPrecio(precio);
        return productoNuevo;
    }
    
    public void validaciones(){
        double precio;
        String nombre = campoNombre.getText().trim();
        String categoria = campoCategoria.getText().trim();
        String pesable = (String) campoPesable.getSelectedItem();
        String descripcion = campoDescripcion.getText().trim();
        String precioTexto = campoPrecioUnidad.getText().trim();
        boolean esPesable = pesable.equals("Sí");
        if (nombre.isEmpty() || categoria.isEmpty() || pesable.isEmpty() ||
        descripcion.isEmpty() || precioTexto.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        precio = Double.parseDouble(precioTexto);
        if (precio < 0) {
            throw new NumberFormatException();
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "El precio debe ser un número válido y positivo.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    crearProductoNuevo(nombre, descripcion, categoria, precio, esPesable);
    JOptionPane.showMessageDialog(null, "Producto registrado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }






}
