/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.ModuloRegistrarEntrada;

import ControlInventario.controlRegistrarEntrada;
import java.time.*;
import javax.swing.*;


/**
 *
 * @author HP
 */
public class menuInventario extends javax.swing.JFrame{
    private controlRegistrarEntrada control;
    /**
     * Creates new form menuInventario
     * @param control
     */
    public menuInventario(controlRegistrarEntrada control) {
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.control = control; 
        this.setTitle("Gestion Inventario");
        this.setSize(1150, 700);
        this.setLocationRelativeTo(null);
        setLocationRelativeTo(null);
        setVisible(true);
        initComponents();
        labelEmpleado.setText("Bienvenido: " + control.cargarEmpleado().getNombre());
        labelFecha.setText("Fecha: " +control.cargarFecha().toLocalDate().toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBtnRegistrarSalida = new javax.swing.JPanel();
        panelBtnRegistrarNuevoProveedor = new javax.swing.JPanel();
        panelBtnRegistrarEntrada = new javax.swing.JPanel();
        labelEmpleado = new javax.swing.JLabel();
        labelEntrada = new javax.swing.JLabel();
        labelSalida = new javax.swing.JLabel();
        labelNuevoProv = new javax.swing.JLabel();
        btnCerrarSesion1 = new javax.swing.JButton();
        labelFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventario");

        panelBtnRegistrarSalida.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout panelBtnRegistrarSalidaLayout = new javax.swing.GroupLayout(panelBtnRegistrarSalida);
        panelBtnRegistrarSalida.setLayout(panelBtnRegistrarSalidaLayout);
        panelBtnRegistrarSalidaLayout.setHorizontalGroup(
            panelBtnRegistrarSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        panelBtnRegistrarSalidaLayout.setVerticalGroup(
            panelBtnRegistrarSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        panelBtnRegistrarNuevoProveedor.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout panelBtnRegistrarNuevoProveedorLayout = new javax.swing.GroupLayout(panelBtnRegistrarNuevoProveedor);
        panelBtnRegistrarNuevoProveedor.setLayout(panelBtnRegistrarNuevoProveedorLayout);
        panelBtnRegistrarNuevoProveedorLayout.setHorizontalGroup(
            panelBtnRegistrarNuevoProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        panelBtnRegistrarNuevoProveedorLayout.setVerticalGroup(
            panelBtnRegistrarNuevoProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        panelBtnRegistrarEntrada.setBackground(new java.awt.Color(102, 102, 102));
        panelBtnRegistrarEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBtnRegistrarEntradaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBtnRegistrarEntradaLayout = new javax.swing.GroupLayout(panelBtnRegistrarEntrada);
        panelBtnRegistrarEntrada.setLayout(panelBtnRegistrarEntradaLayout);
        panelBtnRegistrarEntradaLayout.setHorizontalGroup(
            panelBtnRegistrarEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        panelBtnRegistrarEntradaLayout.setVerticalGroup(
            panelBtnRegistrarEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        labelEmpleado.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelEmpleado.setText("Bienvenido, ");

        labelEntrada.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelEntrada.setText("Registrar Salida de Productos");

        labelSalida.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelSalida.setText("Registrar Nuevo Proveedor");

        labelNuevoProv.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelNuevoProv.setText("Registrar Entrada de Productos");

        btnCerrarSesion1.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCerrarSesion1.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion1.setText("Cerrar sesion");
        btnCerrarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion1ActionPerformed(evt);
            }
        });

        labelFecha.setBackground(new java.awt.Color(0, 0, 0));
        labelFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelFecha.setText("Fecha: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(panelBtnRegistrarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBtnRegistrarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284)
                .addComponent(panelBtnRegistrarNuevoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNuevoProv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                        .addComponent(labelEntrada)
                        .addGap(216, 216, 216)
                        .addComponent(labelSalida)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFecha)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(1041, Short.MAX_VALUE)
                    .addComponent(btnCerrarSesion1)
                    .addGap(27, 27, 27)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(labelEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBtnRegistrarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBtnRegistrarNuevoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBtnRegistrarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNuevoProv, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(labelFecha)
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(629, Short.MAX_VALUE)
                    .addComponent(btnCerrarSesion1)
                    .addGap(38, 38, 38)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelBtnRegistrarEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtnRegistrarEntradaMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1  || evt.getClickCount()==2){
            control.mostrarVentanaSeleccionarProveedor();
        }   
        this.dispose();
    }//GEN-LAST:event_panelBtnRegistrarEntradaMouseClicked

    private void btnCerrarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesion1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion1;
    private javax.swing.JLabel labelEmpleado;
    private javax.swing.JLabel labelEntrada;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelNuevoProv;
    private javax.swing.JLabel labelSalida;
    private javax.swing.JPanel panelBtnRegistrarEntrada;
    private javax.swing.JPanel panelBtnRegistrarNuevoProveedor;
    private javax.swing.JPanel panelBtnRegistrarSalida;
    // End of variables declaration//GEN-END:variables

    
}
