
package GUI.ModuloRegistrarEntrada;

import DTOs.EmpleadoCargadoDTO;
import Exception.InventarioException;
import Exception.NegocioException;
import Exception.VentaException;
import GUI.Aplicacion;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author HP
 */
public class OpcionesInventario extends javax.swing.JPanel {
    private Aplicacion control;
    /**
     * Creates new form OpcionesInventario
     */
    public OpcionesInventario(Aplicacion control) {
        this.control = control;
        initComponents();
        inicializarValoresDefault();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBtnRegistrarEntrada = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelRegistrarEntrada = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JLabel();
        panelBtnRegistrarEntrada1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBtnRegistrarEntrada.setBackground(new java.awt.Color(0, 0, 0));
        panelBtnRegistrarEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBtnRegistrarEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBtnRegistrarEntradaMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar-producto.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBtnRegistrarEntradaLayout = new javax.swing.GroupLayout(panelBtnRegistrarEntrada);
        panelBtnRegistrarEntrada.setLayout(panelBtnRegistrarEntradaLayout);
        panelBtnRegistrarEntradaLayout.setHorizontalGroup(
            panelBtnRegistrarEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnRegistrarEntradaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelBtnRegistrarEntradaLayout.setVerticalGroup(
            panelBtnRegistrarEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnRegistrarEntradaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        add(panelBtnRegistrarEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 230, 190));

        labelRegistrarEntrada.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelRegistrarEntrada.setForeground(new java.awt.Color(0, 0, 0));
        labelRegistrarEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegistrarEntrada.setText("Registrar Entrada");
        add(labelRegistrarEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 230, -1));

        labelFecha.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(0, 0, 0));
        labelFecha.setText("Fecha: ");
        add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Registrar Salida");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 230, -1));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras (1).png"))); // NOI18N
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        panelBtnRegistrarEntrada1.setBackground(new java.awt.Color(0, 0, 0));
        panelBtnRegistrarEntrada1.setForeground(new java.awt.Color(0, 0, 0));
        panelBtnRegistrarEntrada1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBtnRegistrarEntrada1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBtnRegistrarEntrada1MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-producto.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBtnRegistrarEntrada1Layout = new javax.swing.GroupLayout(panelBtnRegistrarEntrada1);
        panelBtnRegistrarEntrada1.setLayout(panelBtnRegistrarEntrada1Layout);
        panelBtnRegistrarEntrada1Layout.setHorizontalGroup(
            panelBtnRegistrarEntrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnRegistrarEntrada1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelBtnRegistrarEntrada1Layout.setVerticalGroup(
            panelBtnRegistrarEntrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnRegistrarEntrada1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        add(panelBtnRegistrarEntrada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 230, 190));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Product Sans Infanity", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Bienvenido, Juanito!");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1150, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void panelBtnRegistrarEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtnRegistrarEntradaMouseClicked
         control.mostrarVentanaHistorialSalidas();
    }//GEN-LAST:event_panelBtnRegistrarEntradaMouseClicked

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        control.mostrarMenuOpciones();
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void panelBtnRegistrarEntrada1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtnRegistrarEntrada1MouseClicked
        try {
            control.mostrarVentanaSeleccionarProveedor();
        } catch (InventarioException ex) {
            Logger.getLogger(OpcionesInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_panelBtnRegistrarEntrada1MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        try {
            control.mostrarVentanaSeleccionarProveedor();
        } catch (InventarioException ex) {
            Logger.getLogger(OpcionesInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         control.mostrarVentanaHistorialSalidas();
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelRegistrarEntrada;
    private javax.swing.JPanel panelBtnRegistrarEntrada;
    private javax.swing.JPanel panelBtnRegistrarEntrada1;
    // End of variables declaration//GEN-END:variables


    public void cargarEmpleado(){
        try {
            EmpleadoCargadoDTO empleado = control.cargarEmpleado();
            
            jLabel5.setText("Bienvenido, " + empleado.getNombre() + "!");
        } catch (VentaException ex) {
            //Tira exception inventario
            Logger.getLogger(OpcionesInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public void inicializarValoresDefault(){
        LocalDateTime fecha = LocalDateTime.now();
        String fechaString = formatearFecha(fecha);
        labelFecha.setText("Fecha: " + fechaString );
        cargarEmpleado();
        
    }
    
    private String formatearFecha(LocalDateTime fecha) {
        if (fecha == null) {
            return "No disponible";
        }
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        return fecha.format(formatter);
    }

}
