/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ModuloRegistrarEntrada;

import Exception.InventarioException;
import Exception.NegocioException;
import GUI.Aplicacion;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author HP
 */
public class OpcionesInventario extends javax.swing.JPanel {
    private Aplicacion control;
    /**
     * Creates new form OpcionesInventario
     */
    public OpcionesInventario(Aplicacion control) {
        this.control = control;
        initComponents();
        inicializarValoresDefault();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBtnRegistrarProveedor = new javax.swing.JPanel();
        panelBtnRegistrarSalida = new javax.swing.JPanel();
        panelBtnRegistrarEntrada = new javax.swing.JPanel();
        labelRegistrarEntrada = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelEmpleado = new javax.swing.JLabel();
        btnAtras = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBtnRegistrarProveedor.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout panelBtnRegistrarProveedorLayout = new javax.swing.GroupLayout(panelBtnRegistrarProveedor);
        panelBtnRegistrarProveedor.setLayout(panelBtnRegistrarProveedorLayout);
        panelBtnRegistrarProveedorLayout.setHorizontalGroup(
            panelBtnRegistrarProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        panelBtnRegistrarProveedorLayout.setVerticalGroup(
            panelBtnRegistrarProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        add(panelBtnRegistrarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 325, -1, -1));

        panelBtnRegistrarSalida.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout panelBtnRegistrarSalidaLayout = new javax.swing.GroupLayout(panelBtnRegistrarSalida);
        panelBtnRegistrarSalida.setLayout(panelBtnRegistrarSalidaLayout);
        panelBtnRegistrarSalidaLayout.setHorizontalGroup(
            panelBtnRegistrarSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        panelBtnRegistrarSalidaLayout.setVerticalGroup(
            panelBtnRegistrarSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        add(panelBtnRegistrarSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 325, -1, -1));

        panelBtnRegistrarEntrada.setBackground(new java.awt.Color(102, 102, 102));
        panelBtnRegistrarEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBtnRegistrarEntradaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBtnRegistrarEntradaLayout = new javax.swing.GroupLayout(panelBtnRegistrarEntrada);
        panelBtnRegistrarEntrada.setLayout(panelBtnRegistrarEntradaLayout);
        panelBtnRegistrarEntradaLayout.setHorizontalGroup(
            panelBtnRegistrarEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        panelBtnRegistrarEntradaLayout.setVerticalGroup(
            panelBtnRegistrarEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        add(panelBtnRegistrarEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 325, -1, -1));

        labelRegistrarEntrada.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelRegistrarEntrada.setText("Registrar Entrada");
        add(labelRegistrarEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 503, -1, -1));

        labelFecha.setText("Fecha: ");
        add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 592, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Registrar Salida");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 503, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Registrar Proveedor");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 503, -1, -1));

        labelEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelEmpleado.setText("Bienvenido, ");
        add(labelEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 55, -1, -1));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras (1).png"))); // NOI18N
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void panelBtnRegistrarEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtnRegistrarEntradaMouseClicked
        try {
            // TODO add your handling code here:
            control.mostrarVentanaSeleccionarProveedor();
        } catch (InventarioException ex) {
            Logger.getLogger(OpcionesInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_panelBtnRegistrarEntradaMouseClicked

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        control.mostrarMenuOpciones();
    }//GEN-LAST:event_btnAtrasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAtras;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelEmpleado;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelRegistrarEntrada;
    private javax.swing.JPanel panelBtnRegistrarEntrada;
    private javax.swing.JPanel panelBtnRegistrarProveedor;
    private javax.swing.JPanel panelBtnRegistrarSalida;
    // End of variables declaration//GEN-END:variables


    public void cargarEmpleado(){
        try {
            labelEmpleado.setText("Bienvenido: " + control.cargarEmpleado().getNombre());
        } catch (NegocioException ex) {
            //Tira exception inventario
            Logger.getLogger(OpcionesInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public void inicializarValoresDefault(){
        labelFecha.setText("Fecha: " + LocalDateTime.now().toString());
        
        
    }

}
