/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ModuloRegistrarEntrada;

import DTOs.EntradaDTO;
import DTOs.ProductoEntradaDTO;
import DTOs.ProductoEntradaDTO;
import Exception.InventarioException;
import Exception.NegocioException;
import GUI.Aplicacion;
import java.awt.BorderLayout;
import java.awt.Component;
import java.time.LocalDateTime;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.security.auth.x500.X500Principal;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
  public class PanelRegistrarProductosEntrada extends javax.swing.JPanel {
    private Aplicacion control;
    private EntradaDTO entrada;
    /**
     * Creates new form registrarProductosEntrada
     * @param control
     */
    public PanelRegistrarProductosEntrada(Aplicacion control) throws InventarioException {
        initComponents();
        setLayout(new BorderLayout());
        this.control = control;
        acomodarPanelArriba();
        acomodarPanelIzquierda();
        acomodarPanelDerecha();
        acomodarPanelAbajo();
        setVisible(true);
    }
    
//idea del acomodar tabla pendiente me fui hacer negocioInventario
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelIzquerda = new javax.swing.JPanel();
        btnAgregarProductoEntrada = new javax.swing.JButton();
        scrollTablaProductosEntrada = new javax.swing.JScrollPane();
        tablaProductosEntrada = new javax.swing.JTable();
        PanelDerecha = new javax.swing.JPanel();
        panelSumatorias = new javax.swing.JPanel();
        separadorPrecioCompra = new javax.swing.JSeparator();
        btnCancelarRegistro = new javax.swing.JButton();
        btnAgregarProductoInventario = new javax.swing.JButton();
        PanelArriba = new javax.swing.JPanel();
        labelRegistrarProd = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 5));
        labelEmpleado = new javax.swing.JLabel();
        PanelAbajo = new javax.swing.JPanel();
        labelFecha = new javax.swing.JLabel();
        PanelBotones = new javax.swing.JPanel();
        btnConfirmarEntrada = new javax.swing.JButton();
        bordeSur = new javax.swing.JSeparator();
        bordeNorte = new javax.swing.JSeparator();
        labelSubtotal = new javax.swing.JLabel();
        campoTotal = new javax.swing.JTextField();
        labelTotal = new javax.swing.JLabel();
        campoSubtotal = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(980, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));

        PanelIzquerda.setMaximumSize(new java.awt.Dimension(600, 280));
        PanelIzquerda.setPreferredSize(new java.awt.Dimension(600, 280));
        PanelIzquerda.setLayout(new java.awt.BorderLayout());

        btnAgregarProductoEntrada.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregarProductoEntrada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregarProductoEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProductoEntrada.setText("+");
        btnAgregarProductoEntrada.setToolTipText("Agregar Producto a la Entrada");
        btnAgregarProductoEntrada.setMaximumSize(new java.awt.Dimension(50, 20));
        btnAgregarProductoEntrada.setMinimumSize(new java.awt.Dimension(32, 20));
        btnAgregarProductoEntrada.setPreferredSize(new java.awt.Dimension(50, 20));
        btnAgregarProductoEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarProductoEntradaMouseClicked(evt);
            }
        });
        PanelIzquerda.add(btnAgregarProductoEntrada, java.awt.BorderLayout.PAGE_START);
        btnAgregarProductoEntrada.getAccessibleContext().setAccessibleDescription("");

        scrollTablaProductosEntrada.setBorder(null);
        scrollTablaProductosEntrada.setMaximumSize(new java.awt.Dimension(600, 280));
        scrollTablaProductosEntrada.setPreferredSize(new java.awt.Dimension(500, 280));

        tablaProductosEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProductosEntrada.setMaximumSize(new java.awt.Dimension(600, 280));
        tablaProductosEntrada.setPreferredSize(new java.awt.Dimension(600, 280));
        tablaProductosEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosEntradaMouseClicked(evt);
            }
        });
        scrollTablaProductosEntrada.setViewportView(tablaProductosEntrada);

        PanelIzquerda.add(scrollTablaProductosEntrada, java.awt.BorderLayout.WEST);

        PanelDerecha.setMaximumSize(new java.awt.Dimension(300, 330));
        PanelDerecha.setMinimumSize(new java.awt.Dimension(300, 158));
        PanelDerecha.setPreferredSize(new java.awt.Dimension(300, 330));

        panelSumatorias.setMaximumSize(new java.awt.Dimension(150, 100));
        panelSumatorias.setPreferredSize(new java.awt.Dimension(150, 100));
        panelSumatorias.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        separadorPrecioCompra.setForeground(new java.awt.Color(242, 242, 242));
        separadorPrecioCompra.setMaximumSize(new java.awt.Dimension(50, 20));
        panelSumatorias.add(separadorPrecioCompra);

        btnCancelarRegistro.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelarRegistro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancelarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarRegistro.setText("Cancelar Registro de Entrada");
        btnCancelarRegistro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelarRegistro.setMaximumSize(new java.awt.Dimension(280, 32));
        btnCancelarRegistro.setPreferredSize(new java.awt.Dimension(280, 32));
        btnCancelarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarRegistroMouseClicked(evt);
            }
        });

        btnAgregarProductoInventario.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregarProductoInventario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregarProductoInventario.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProductoInventario.setText("Agregar prod. al inventario");
        btnAgregarProductoInventario.setToolTipText("");
        btnAgregarProductoInventario.setMaximumSize(new java.awt.Dimension(280, 70));
        btnAgregarProductoInventario.setPreferredSize(new java.awt.Dimension(280, 60));
        btnAgregarProductoInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarProductoInventarioMouseClicked(evt);
            }
        });
        btnAgregarProductoInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDerechaLayout = new javax.swing.GroupLayout(PanelDerecha);
        PanelDerecha.setLayout(PanelDerechaLayout);
        PanelDerechaLayout.setHorizontalGroup(
            PanelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDerechaLayout.createSequentialGroup()
                .addGroup(PanelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAgregarProductoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelDerechaLayout.createSequentialGroup()
                            .addComponent(panelSumatorias, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(167, 167, 167)))
                    .addGroup(PanelDerechaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCancelarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelDerechaLayout.setVerticalGroup(
            PanelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDerechaLayout.createSequentialGroup()
                .addComponent(panelSumatorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnAgregarProductoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        PanelArriba.setMaximumSize(new java.awt.Dimension(1200, 100));
        PanelArriba.setPreferredSize(new java.awt.Dimension(1200, 100));
        PanelArriba.setLayout(new javax.swing.BoxLayout(PanelArriba, javax.swing.BoxLayout.LINE_AXIS));

        labelRegistrarProd.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelRegistrarProd.setText("Informarcion de la Entrada");
        labelRegistrarProd.setMaximumSize(new java.awt.Dimension(500, 50));
        labelRegistrarProd.setMinimumSize(new java.awt.Dimension(500, 50));
        labelRegistrarProd.setPreferredSize(new java.awt.Dimension(500, 48));
        PanelArriba.add(labelRegistrarProd);
        PanelArriba.add(filler2);
        filler2.getAccessibleContext().setAccessibleName("");

        labelEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelEmpleado.setMaximumSize(new java.awt.Dimension(390, 100));
        labelEmpleado.setPreferredSize(new java.awt.Dimension(200, 100));
        PanelArriba.add(labelEmpleado);

        PanelAbajo.setMaximumSize(new java.awt.Dimension(980, 150));
        PanelAbajo.setPreferredSize(new java.awt.Dimension(980, 150));
        PanelAbajo.setLayout(new java.awt.BorderLayout());

        labelFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelFecha.setText("Fecha");
        labelFecha.setToolTipText("");
        labelFecha.setMaximumSize(new java.awt.Dimension(200, 100));
        PanelAbajo.add(labelFecha, java.awt.BorderLayout.WEST);

        PanelBotones.setMaximumSize(new java.awt.Dimension(300, 60));
        PanelBotones.setPreferredSize(new java.awt.Dimension(300, 60));
        PanelBotones.setLayout(new java.awt.BorderLayout());

        btnConfirmarEntrada.setBackground(new java.awt.Color(0, 0, 0));
        btnConfirmarEntrada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConfirmarEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarEntrada.setText("Confirmar Registro");
        btnConfirmarEntrada.setMaximumSize(new java.awt.Dimension(235, 35));
        btnConfirmarEntrada.setPreferredSize(new java.awt.Dimension(235, 35));
        btnConfirmarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarEntradaActionPerformed(evt);
            }
        });
        PanelBotones.add(btnConfirmarEntrada, java.awt.BorderLayout.CENTER);

        PanelAbajo.add(PanelBotones, java.awt.BorderLayout.EAST);

        bordeSur.setForeground(new java.awt.Color(242, 242, 242));
        bordeSur.setMaximumSize(new java.awt.Dimension(50, 20));
        bordeSur.setPreferredSize(new java.awt.Dimension(0, 20));
        PanelAbajo.add(bordeSur, java.awt.BorderLayout.SOUTH);

        bordeNorte.setMaximumSize(new java.awt.Dimension(980, 20));
        bordeNorte.setPreferredSize(new java.awt.Dimension(0, 20));
        PanelAbajo.add(bordeNorte, java.awt.BorderLayout.NORTH);

        labelSubtotal.setText("Subtotal:");

        campoTotal.setEnabled(false);
        campoTotal.setInheritsPopupMenu(true);
        campoTotal.setMaximumSize(new java.awt.Dimension(250, 25));
        campoTotal.setPreferredSize(new java.awt.Dimension(250, 25));

        labelTotal.setText("Total: ");

        campoSubtotal.setEnabled(false);
        campoSubtotal.setInheritsPopupMenu(true);
        campoSubtotal.setMaximumSize(new java.awt.Dimension(250, 25));
        campoSubtotal.setPreferredSize(new java.awt.Dimension(250, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelIzquerda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(PanelDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSubtotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTotal)
                        .addGap(27, 27, 27)
                        .addComponent(campoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelArriba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelIzquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelDerecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSubtotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotal)
                    .addComponent(campoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarEntradaActionPerformed
        // TODO add your handling code here:
         entrada = control.getEntradaTemporal();
        try {
            JOptionPane.showConfirmDialog(null, "¿Desea registrar la entrada?");
            control.registrarEntrada(entrada);
        } catch (InventarioException ex) {
            Logger.getLogger(PanelRegistrarProductosEntrada.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConfirmarEntradaActionPerformed

    private void tablaProductosEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosEntradaMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
                    //control.EliminarProductoEntrada(tablaProductosEntrada.getSelectedRow());
        }
        //Actualizar la tabla para eliminar el producto
    }//GEN-LAST:event_tablaProductosEntradaMouseClicked

    private void btnAgregarProductoInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProductoInventarioMouseClicked
        // TODO add your handling code here:
        control.mostrarVentanaProductoNuevo();
    }//GEN-LAST:event_btnAgregarProductoInventarioMouseClicked

    private void btnCancelarRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarRegistroMouseClicked
        // TODO add your handling code here:                   
    }//GEN-LAST:event_btnCancelarRegistroMouseClicked

    private void btnAgregarProductoEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProductoEntradaMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
            try {
                control.mostrarVentanaSeleccionarProductosEntrada();
            } catch (NegocioException ex) {
                Logger.getLogger(PanelRegistrarProductosEntrada.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnAgregarProductoEntradaMouseClicked

    private void btnAgregarProductoInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoInventarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAgregarProductoInventarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAbajo;
    private javax.swing.JPanel PanelArriba;
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelDerecha;
    private javax.swing.JPanel PanelIzquerda;
    private javax.swing.JSeparator bordeNorte;
    private javax.swing.JSeparator bordeSur;
    private javax.swing.JButton btnAgregarProductoEntrada;
    private javax.swing.JButton btnAgregarProductoInventario;
    private javax.swing.JButton btnCancelarRegistro;
    private javax.swing.JButton btnConfirmarEntrada;
    private javax.swing.JTextField campoSubtotal;
    private javax.swing.JTextField campoTotal;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel labelEmpleado;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelRegistrarProd;
    private javax.swing.JLabel labelSubtotal;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JPanel panelSumatorias;
    private javax.swing.JScrollPane scrollTablaProductosEntrada;
    private javax.swing.JSeparator separadorPrecioCompra;
    private javax.swing.JTable tablaProductosEntrada;
    // End of variables declaration//GEN-END:variables
    public void valoresd(){
        //contorl.getEntrada
    }
    
    
    public void acomodarPanelArriba() throws InventarioException{
        try {
            labelEmpleado.setText("Empleado: "+ control.cargarEmpleado().getNombre());
        } catch (NegocioException ex) {
            throw new InventarioException("Error al cargar Empleado");
        }
        PanelArriba.add(Box.createHorizontalStrut(100));
        this.add(PanelArriba, BorderLayout.NORTH);
    }
    public void acomodarPanelAbajo(){
        labelFecha.setText("Fecha: " + LocalDateTime.now().toString());
        PanelAbajo.add(Box.createHorizontalStrut(50));        
        this.add(PanelAbajo, BorderLayout.SOUTH);
    }

    public void acomodarPanelIzquierda(){
        crearTablaProductosEntrada();
        this.revalidate();
        this.repaint();
        btnAgregarProductoEntrada.setAlignmentY(Component.RIGHT_ALIGNMENT);
        PanelIzquerda.add(btnAgregarProductoEntrada,BorderLayout.EAST);    
        PanelIzquerda.add(scrollTablaProductosEntrada, BorderLayout.WEST);
        this.add(PanelIzquerda, BorderLayout.WEST);   
    }
    public void acomodarPanelDerecha(){
        panelSumatorias.setAlignmentX(Component.LEFT_ALIGNMENT);  
        btnCancelarRegistro.setAlignmentX(Component.LEFT_ALIGNMENT);
        btnAgregarProductoInventario.setAlignmentX(Component.LEFT_ALIGNMENT);
        this.add(PanelDerecha, BorderLayout.EAST);
    }
    
    public void crearTablaProductosEntrada(){   
        String StringprecioCompra;
        String Total;
        String subtotal;
        String Stringimporte;
        double importe;
        double precioCompra;
        double subtotalTemporal =0.0;
        String columnasTabla[] = {"ID","Nombre","unidad", "Precio de Compra", "Importe"};
        tablaProductosEntrada.setRowHeight(25);
        DefaultTableModel modelo = new DefaultTableModel(columnasTabla, 0){
            @Override
            public boolean  isCellEditable(int fila, int columna){
                return false;
            }                    
        };
        tablaProductosEntrada.setRowSelectionAllowed(true);
        tablaProductosEntrada.setColumnSelectionAllowed(false);
        tablaProductosEntrada.getTableHeader().setReorderingAllowed(false);
        tablaProductosEntrada.getTableHeader().setResizingAllowed(false);
            for(ProductoEntradaDTO producto : control.cargarProductosEntrada()){
                precioCompra = producto.getPrecioCompra();
                StringprecioCompra = String.format("%.2f", precioCompra);
                importe = producto.getUnidad()*producto.getPrecioCompra();
                Stringimporte = String.format("%.2f", importe);
                modelo.addRow(new Object[]{
                    producto.getProductoEntrada().getCodigo(),
                    producto.getProductoEntrada().getNombre(),
                    producto.getUnidad(),
                    StringprecioCompra,
                    Stringimporte 
                    }               
                );           
                subtotalTemporal+=importe;  
            }
        tablaProductosEntrada.setModel(modelo);
        double total =subtotalTemporal;
        subtotal = String.format("%.2f", subtotalTemporal);
        Total = String.format("%.2f", total);
        campoSubtotal.setText(subtotal);
        campoTotal.setText(Total);
    }
  
  }
