/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ModuloRegistrarEntrada;

import DTOs.EntradaDTO;
import DTOs.ProductoEntradaDTO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ResumenEntrada extends javax.swing.JPanel {
    private EntradaDTO entrada;
    /**
     * Creates new form ResumenEntrada
     */
    public ResumenEntrada(EntradaDTO entrada) {
        this.entrada = entrada; 
        initComponents();
        valoresDefault();
        crearTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelProveedor = new javax.swing.JLabel();
        labelSubtotal = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        CampoProveedor = new javax.swing.JLabel();
        CampoSubtotal = new javax.swing.JLabel();
        CampoTotal = new javax.swing.JLabel();
        tablaProductosentrada = new javax.swing.JScrollPane();
        TablaProductosEntrada = new javax.swing.JTable();
        BtnMenuPrincipal = new javax.swing.JButton();
        BtnReportePdf1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelProveedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelProveedor.setText("Proveedor");
        add(labelProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        labelSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelSubtotal.setText("Subtotal");
        add(labelSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        labelTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTotal.setText("Total");
        add(labelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitulo.setText("Resumen de Entrada");
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        CampoProveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CampoProveedor.setText("jLabel1");
        add(CampoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 20));

        CampoSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CampoSubtotal.setText("subtotal");
        add(CampoSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, -1));

        CampoTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CampoTotal.setText("total");
        add(CampoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 60, -1));

        TablaProductosEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProductosentrada.setViewportView(TablaProductosEntrada);

        add(tablaProductosentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        BtnMenuPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        BtnMenuPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        BtnMenuPrincipal.setText("Menu Principal");
        BtnMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMenuPrincipalMouseClicked(evt);
            }
        });
        add(BtnMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 580, 150, -1));

        BtnReportePdf1.setBackground(new java.awt.Color(0, 0, 0));
        BtnReportePdf1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnReportePdf1.setForeground(new java.awt.Color(255, 255, 255));
        BtnReportePdf1.setText("Reporte pdf");
        BtnReportePdf1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnReportePdf1MouseClicked(evt);
            }
        });
        add(BtnReportePdf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMenuPrincipalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMenuPrincipalMouseClicked

    private void BtnReportePdf1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnReportePdf1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnReportePdf1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMenuPrincipal;
    private javax.swing.JButton BtnReportePdf1;
    private javax.swing.JLabel CampoProveedor;
    private javax.swing.JLabel CampoSubtotal;
    private javax.swing.JLabel CampoTotal;
    private javax.swing.JTable TablaProductosEntrada;
    private javax.swing.JLabel labelProveedor;
    private javax.swing.JLabel labelSubtotal;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JScrollPane tablaProductosentrada;
    // End of variables declaration//GEN-END:variables
    
    public void valoresDefault(){
        String subtotal, total;
        labelProveedor.setText(entrada.getProveedor().getNombre());
        subtotal = String.format("%.2f", entrada.getSubtotal());
        total = String.format("%.2f", entrada.getTotal());
        labelSubtotal.setText(subtotal);
        CampoTotal.setText(total);
    }
    
    public void crearTabla(){
        String[] columnas = {"Producto", "Cantidad", "Precio Compra", "Importe"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        TablaProductosEntrada.setModel(modelo);
        for (ProductoEntradaDTO producto : entrada.getListaProductosEntrada()) {
            String nombre = producto.getProductoEntrada().getNombre();
            double cantidad = producto.getStock();
            double precio = producto.getPrecioCompra();
            double importe = cantidad * precio;
            modelo.addRow(new Object[]{nombre, cantidad, "$" + precio, "$" + importe});
        }
    }
    

}
