
package GUI.ModuloRegistrarEntrada;

import DTOs.ProveedorDTO;
import Exception.InventarioException;
import Exception.NegocioException;
import GUI.Aplicacion;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class SeleccionarProveedor extends javax.swing.JPanel {
    private Aplicacion control;
    private ProveedorDTO proveedorSeleccionado;
 
    
    /**
     * Creates new form ProveedorSeleccionado
     */
    public SeleccionarProveedor(Aplicacion control) throws InventarioException {
        this.control = control;
        initComponents();
        cargarTabla();
        setVisible(true);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSeleccionProv = new javax.swing.JLabel();
        panelTablaProveedores = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        btnAtras = new javax.swing.JLabel();

        setToolTipText("");
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSeleccionProv.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelSeleccionProv.setText("Seleccion de Proveedor");
        add(labelSeleccionProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        tablaProveedores.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProveedores.setRowHeight(35);
        tablaProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProveedoresMouseClicked(evt);
            }
        });
        panelTablaProveedores.setViewportView(tablaProveedores);

        add(panelTablaProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 123, 440, 500));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras (1).png"))); // NOI18N
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void tablaProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProveedoresMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            try { 
                proveedorSeleccionado = control.cargarProveedores().get(tablaProveedores.getSelectedRow());
                setearProveedor();
                control.mostrarVentanaSeleccionarProductosEntrada();
            } catch (InventarioException | NegocioException ex) {
                Logger.getLogger(SeleccionarProveedor.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_tablaProveedoresMouseClicked

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        control.mostrarVentanaOpcionesInventario();
    }//GEN-LAST:event_btnAtrasMouseClicked

    public void setearProveedor(){
        control.setProveedor(proveedorSeleccionado);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAtras;
    private javax.swing.JLabel labelSeleccionProv;
    private javax.swing.JScrollPane panelTablaProveedores;
    private javax.swing.JTable tablaProveedores;
    // End of variables declaration//GEN-END:variables
    
 
    public void cargarTabla() throws InventarioException {
        List<ProveedorDTO> listaProveedores;
        try {
            listaProveedores = control.cargarProveedores();
            DefaultTableModel model = (DefaultTableModel) tablaProveedores.getModel();
            model.setRowCount(0);
            
            for (ProveedorDTO proveedor : listaProveedores) {
                Object[] fila = new Object[]{
                    proveedor.getNombre(),
                    proveedor.getTelefono()
                };
                model.addRow(fila);
            }
        } catch (InventarioException ex) {
            throw new InventarioException("Error al cargar Proveedores");
        }

    }
    
}

