/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ModuloRealizarVenta;

import DTOs.NuevoProductoVentaDTO;
import DTOs.ProductoVentaDTO;
import DTOs.TicketDTO;
import DTOs.VentaDTO;
import GUI.Aplicacion;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import static javax.swing.Box.createVerticalGlue;
import javax.swing.BoxLayout;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class generarTicketVenta extends javax.swing.JPanel {

    public Aplicacion app;
    public VentaDTO venta;
    public double subtotal, iva, total;

    /**
     * Creates new form vistaTicketPDF
     *
     * @param app
     *
     */
    public generarTicketVenta(Aplicacion app) {
        initComponents();
        this.app = app;
        this.venta = app.obtenerVenta();
        crearTicket();
        acomodarTicket();
        acomodarPanelTabla();
        acomodarPanelSumas();
        acomodarPanelBotones();
        generarTicketVenta();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ticket = new javax.swing.JLabel();
        campoCarniceria = new javax.swing.JLabel();
        panelSumas = new javax.swing.JPanel();
        campoSubtotal = new javax.swing.JLabel();
        campoIVA = new javax.swing.JLabel();
        campoTotalVenta = new javax.swing.JLabel();
        campoSubtotal2 = new javax.swing.JLabel();
        campoIVATotal = new javax.swing.JLabel();
        campoTotal = new javax.swing.JLabel();
        campoFechaVenta = new javax.swing.JLabel();
        campoEmpleado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTicket = new javax.swing.JTable();
        panelBotones = new javax.swing.JPanel();
        btnImprimirTicket = new javax.swing.JButton();
        btnSalirTicket = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        ticket.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ticket.setText("Ticket de Compra");
        add(ticket);

        campoCarniceria.setText("Carniceria");
        add(campoCarniceria);

        campoSubtotal.setText("Subtotal:  ");
        panelSumas.add(campoSubtotal);

        campoIVA.setText("IVA:");
        panelSumas.add(campoIVA);

        campoTotalVenta.setText("Total:");
        panelSumas.add(campoTotalVenta);

        campoSubtotal2.setText("jLabel1");
        panelSumas.add(campoSubtotal2);

        campoIVATotal.setText("jLabel2");
        panelSumas.add(campoIVATotal);

        campoTotal.setText("jLabel3");
        panelSumas.add(campoTotal);

        add(panelSumas);

        campoFechaVenta.setText("jLabel3");
        add(campoFechaVenta);

        campoEmpleado.setText("jLabel1");
        add(campoEmpleado);

        jScrollPane1.setBorder(null);

        tablaTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaTicket);

        add(jScrollPane1);

        btnImprimirTicket.setBackground(new java.awt.Color(0, 0, 0));
        btnImprimirTicket.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimirTicket.setText("Imprimir");
        btnImprimirTicket.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panelBotones.add(btnImprimirTicket);

        btnSalirTicket.setBackground(new java.awt.Color(102, 102, 102));
        btnSalirTicket.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirTicket.setText("Salir");
        btnSalirTicket.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSalirTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirTicketActionPerformed(evt);
            }
        });
        panelBotones.add(btnSalirTicket);

        add(panelBotones);
        panelBotones.getAccessibleContext().setAccessibleName("");
        panelBotones.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirTicketActionPerformed
        // TODO add your handling code here:

        ((JDialog) SwingUtilities.getWindowAncestor((JComponent) evt.getSource())).dispose();
        app.reconstruirRegistrarVenta();
    }//GEN-LAST:event_btnSalirTicketActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimirTicket;
    private javax.swing.JButton btnSalirTicket;
    private javax.swing.JLabel campoCarniceria;
    private javax.swing.JLabel campoEmpleado;
    private javax.swing.JLabel campoFechaVenta;
    private javax.swing.JLabel campoIVA;
    private javax.swing.JLabel campoIVATotal;
    private javax.swing.JLabel campoSubtotal;
    private javax.swing.JLabel campoSubtotal2;
    private javax.swing.JLabel campoTotal;
    private javax.swing.JLabel campoTotalVenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelSumas;
    private javax.swing.JTable tablaTicket;
    private javax.swing.JLabel ticket;
    // End of variables declaration//GEN-END:variables

    public TicketDTO crearTicket() {
        return app.crearTicket(venta);
    }

    public void acomodarTicket() {
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        ticket.setAlignmentX(CENTER_ALIGNMENT);
        campoCarniceria.setAlignmentX(CENTER_ALIGNMENT);
        campoEmpleado.setAlignmentX(CENTER_ALIGNMENT);
        campoFechaVenta.setAlignmentX(CENTER_ALIGNMENT);
    }

    public void acomodarPanelSumas() {
        panelSumas.setLayout(new GridLayout(3, 2));
        panelSumas.add(campoSubtotal);
        panelSumas.add(campoSubtotal2);
        panelSumas.add(campoIVA);
        panelSumas.add(campoIVATotal);
        panelSumas.add(campoTotalVenta);
        panelSumas.add(campoTotal);
        add(panelSumas);
    }

    public void acomodarPanelTabla() {
        tablaTicket.setEnabled(false);
        tablaTicket.getTableHeader().setReorderingAllowed(false);
        jScrollPane1 = new JScrollPane(tablaTicket);
        add(jScrollPane1);
    }

    public void acomodarPanelBotones() {
        panelBotones.setLayout(new FlowLayout());
        panelBotones.add(btnImprimirTicket);
        panelBotones.add(btnSalirTicket);
        add(panelBotones);
    }

    public void generarTicketVenta() {
        TicketDTO ticket = crearTicket();
        String columnasTabla[] = {"Producto", "cantidad", "subtotal"};
        campoEmpleado.setText(ticket.getCajero().getNombre());
        campoFechaVenta.setText(ticket.getFechaHora().format(DateTimeFormatter.ISO_DATE));
        DefaultTableModel modelo = new DefaultTableModel(columnasTabla, 0);

        for (ProductoVentaDTO producto : ticket.getListaProductosVenta()) {
            modelo.addRow(new Object[]{producto.getProducto().getNombre(), producto.getCantidad(), producto.getCantidad() * producto.getImporte()});
        }
        tablaTicket.setModel(modelo);
        tablaTicket.setVisible(true);
        tablaTicket.setEnabled(false);
        subtotal = calcularSubtotal((ArrayList<ProductoVentaDTO>) ticket.getListaProductosVenta());
        iva = calcularIva(subtotal);
        total = calcularTotal(subtotal, iva);
        campoSubtotal2.setText(String.format("%.2f", subtotal));
        campoIVATotal.setText(String.format("%.2f", iva));
        campoTotal.setText(String.format("%.2f", total));
    }

    public double calcularSubtotal(ArrayList<ProductoVentaDTO> productosEnTabla) {
        double subtotal = 0.0;
        for (ProductoVentaDTO nuevoProductoVentaDTO : productosEnTabla) {
            double precioConIva = nuevoProductoVentaDTO.getImporte();
            subtotal += precioConIva / 1.16; // Quitar el IVA para obtener el subtotal
        }
        return subtotal;
    }

    public double calcularIva(double subtotal) {
        return subtotal * 0.16; // 16% de IVA
    }

    public double calcularTotal(double subtotal, double iva) {
        return subtotal + iva;
    }
}
