/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ModuloRealizarVenta;

import GUI.Aplicacion;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class MenuOpciones extends javax.swing.JPanel {

    Aplicacion app;

    /**
     * Creates new form MenuOpciones
     */
    public MenuOpciones(Aplicacion app) {
        this.app = app;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotonVentaEnCaja = new javax.swing.JPanel();
        icnRealizarVenta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelRound1 = new GUI.PanelRound();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBotonVentaEnCaja.setBackground(new java.awt.Color(73, 69, 79));
        pnlBotonVentaEnCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBotonVentaEnCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBotonVentaEnCajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBotonVentaEnCajaMouseExited(evt);
            }
        });
        pnlBotonVentaEnCaja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icnRealizarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icnRealizarVenta.png"))); // NOI18N
        icnRealizarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icnRealizarVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icnRealizarVentaMouseEntered(evt);
            }
        });
        pnlBotonVentaEnCaja.add(icnRealizarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 130, 150));

        add(pnlBotonVentaEnCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 190, 170));

        jLabel2.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        jLabel2.setText("Venta en caja");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 150, 30));

        panelRound1.setBackground(new java.awt.Color(44, 44, 44));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cerrar Sesion");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 120, 40));

        add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 600, 220, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void icnRealizarVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icnRealizarVentaMouseEntered
        // TODO add your handling code here:
        pnlBotonVentaEnCaja.setBackground(new Color(100, 100, 120, 180));

    }//GEN-LAST:event_icnRealizarVentaMouseEntered

    private void pnlBotonVentaEnCajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBotonVentaEnCajaMouseEntered
        // TODO add your handling code here:
        pnlBotonVentaEnCaja.setBackground(new Color(100, 100, 120, 180));
    }//GEN-LAST:event_pnlBotonVentaEnCajaMouseEntered

    private void pnlBotonVentaEnCajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBotonVentaEnCajaMouseExited
        // TODO add your handling code here:
        pnlBotonVentaEnCaja.setBackground(new Color(73, 69, 79, 150));
    }//GEN-LAST:event_pnlBotonVentaEnCajaMouseExited

    private void icnRealizarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icnRealizarVentaMouseClicked
        app.mostrarPantallaMenuDevolucion();
    }//GEN-LAST:event_icnRealizarVentaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icnRealizarVenta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private GUI.PanelRound panelRound1;
    private javax.swing.JPanel pnlBotonVentaEnCaja;
    // End of variables declaration//GEN-END:variables
}
