package GUI.ModuloRealizarVenta;

/**
 *
 * @author Lap-064
 */
import DTOs.EmpleadoCargadoDTO;
import DTOs.NuevoProductoVentaDTO;
import DTOs.ProductoCargadoDTO;
import DTOs.ProductoVentaDTO;
import DTOs.VentaDTO;
import Exception.NegocioException;
import Exception.VentaException;
import GUI.Aplicacion;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.DefaultListModel;
import javax.swing.InputMap;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

public class RegistrarVenta extends javax.swing.JPanel {

    /**
     * Creates new form RealizarVenta
     */
    private Aplicacion app;
    private List<ProductoCargadoDTO> listadoProductosCargados = new ArrayList<>();
    private ArrayList<ProductoVentaDTO> listadoProductosVenta = new ArrayList<>();

    public RegistrarVenta(Aplicacion app) {
        this.app = app;
        initComponents();

        try {

            inicializarValoresDefault();
        } catch (NegocioException ex) {
            Logger.getLogger(RegistrarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCajero = new javax.swing.JLabel();
        tblProductosVenta = new javax.swing.JScrollPane();
        tablaProductosVenta = new javax.swing.JTable();
        pnlTotal = new GUI.PanelRound();
        txtSubtotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtIva = new javax.swing.JLabel();
        btnFinalizarVenta = new GUI.PanelRound();
        btnTxtFinalizarVenta = new javax.swing.JLabel();
        btnTarjeta = new GUI.PanelRound();
        btnTxtTarjeta = new javax.swing.JLabel();
        btnEfectivo = new GUI.PanelRound();
        btnTxtEfectivo = new javax.swing.JLabel();
        listaProductos = new javax.swing.JScrollPane();
        listadoGraficoProductosCargados = new javax.swing.JList<>();
        txtBusquedaNombre = new javax.swing.JLabel();
        txtBusquedaCodigo = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        inputCodigo = new javax.swing.JTextField();
        txtPanelVentaEnCaja = new javax.swing.JLabel();
        btnAtras = new javax.swing.JLabel();
        btnReiniciarVenta = new javax.swing.JLabel();
        btnAtajos = new GUI.PanelRound();
        btnConsultarAtajos = new javax.swing.JLabel();
        txtBusquedaNombre1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCajero.setBackground(new java.awt.Color(0, 0, 0));
        txtCajero.setFont(new java.awt.Font("Product Sans Infanity", 0, 36)); // NOI18N
        txtCajero.setText("Cajero:");
        add(txtCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        tablaProductosVenta.setBackground(new java.awt.Color(217, 217, 217));
        tablaProductosVenta.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        tablaProductosVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripción del articulo", "Cantidad", "Precio", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductosVenta.setFocusable(false);
        tablaProductosVenta.setRowHeight(40);
        tablaProductosVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosVentaMouseClicked(evt);
            }
        });
        tblProductosVenta.setViewportView(tablaProductosVenta);

        add(tblProductosVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 880, 370));

        pnlTotal.setBackground(new java.awt.Color(240, 244, 244));
        pnlTotal.setFont(new java.awt.Font("Product Sans Infanity", 0, 12)); // NOI18N
        pnlTotal.setRoundBottomLeft(30);
        pnlTotal.setRoundBottomRight(30);
        pnlTotal.setRoundTopLeft(30);
        pnlTotal.setRoundTopRight(30);
        pnlTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSubtotal.setBackground(new java.awt.Color(0, 0, 0));
        txtSubtotal.setFont(new java.awt.Font("Product Sans Infanity", 0, 30)); // NOI18N
        txtSubtotal.setText("Subtotal: $0.00");
        pnlTotal.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, -1));

        txtTotal.setBackground(new java.awt.Color(0, 0, 0));
        txtTotal.setFont(new java.awt.Font("Product Sans Infanity", 0, 36)); // NOI18N
        txtTotal.setText("Total: $0.00");
        pnlTotal.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, -1));

        txtIva.setBackground(new java.awt.Color(0, 0, 0));
        txtIva.setFont(new java.awt.Font("Product Sans Infanity", 0, 30)); // NOI18N
        txtIva.setText("IVA(16%): $0.00");
        pnlTotal.add(txtIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, -1));

        add(pnlTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 220, 220, 220));

        btnFinalizarVenta.setBackground(new java.awt.Color(44, 44, 44));
        btnFinalizarVenta.setRoundBottomLeft(15);
        btnFinalizarVenta.setRoundBottomRight(15);
        btnFinalizarVenta.setRoundTopLeft(15);
        btnFinalizarVenta.setRoundTopRight(15);
        btnFinalizarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizarVentaMouseClicked(evt);
            }
        });
        btnFinalizarVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTxtFinalizarVenta.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        btnTxtFinalizarVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnTxtFinalizarVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTxtFinalizarVenta.setText("Finalizar Venta");
        btnTxtFinalizarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinalizarVenta.add(btnTxtFinalizarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 210, 70));

        add(btnFinalizarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, 290, 70));

        btnTarjeta.setBackground(new java.awt.Color(44, 44, 44));
        btnTarjeta.setRoundBottomLeft(15);
        btnTarjeta.setRoundBottomRight(15);
        btnTarjeta.setRoundTopLeft(15);
        btnTarjeta.setRoundTopRight(15);
        btnTarjeta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTxtTarjeta.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        btnTxtTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        btnTxtTarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTxtTarjeta.setText("Tarjeta");
        btnTxtTarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTxtTarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTxtTarjetaMouseClicked(evt);
            }
        });
        btnTarjeta.add(btnTxtTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        add(btnTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 460, 220, 50));

        btnEfectivo.setBackground(new java.awt.Color(44, 44, 44));
        btnEfectivo.setRoundBottomLeft(15);
        btnEfectivo.setRoundBottomRight(15);
        btnEfectivo.setRoundTopLeft(15);
        btnEfectivo.setRoundTopRight(15);
        btnEfectivo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTxtEfectivo.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        btnTxtEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        btnTxtEfectivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTxtEfectivo.setText("Efectivo");
        btnTxtEfectivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTxtEfectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTxtEfectivoMouseClicked(evt);
            }
        });
        btnEfectivo.add(btnTxtEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        add(btnEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 520, 220, 50));

        listadoGraficoProductosCargados.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        listadoGraficoProductosCargados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listadoGraficoProductosCargados.setFocusable(false);
        listadoGraficoProductosCargados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoGraficoProductosCargadosMouseClicked(evt);
            }
        });
        listadoGraficoProductosCargados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listadoGraficoProductosCargadosKeyPressed(evt);
            }
        });
        listaProductos.setViewportView(listadoGraficoProductosCargados);

        add(listaProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 760, 140));

        txtBusquedaNombre.setFont(new java.awt.Font("Product Sans Infanity", 0, 17)); // NOI18N
        txtBusquedaNombre.setText("Ctrl + A para consultar Atajos");
        add(txtBusquedaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 230, 30));

        txtBusquedaCodigo.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaCodigo.setText("Busqueda Codigo:");
        add(txtBusquedaCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 210, 30));

        inputNombre.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        inputNombre.setText("Nombre Producto");
        inputNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNombreFocusLost(evt);
            }
        });
        inputNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNombreKeyTyped(evt);
            }
        });
        add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 160, 30));

        inputCodigo.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        inputCodigo.setText("Codigo");
        inputCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputCodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputCodigoFocusLost(evt);
            }
        });
        inputCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputCodigoKeyTyped(evt);
            }
        });
        add(inputCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 150, 30));

        txtPanelVentaEnCaja.setBackground(new java.awt.Color(0, 0, 0));
        txtPanelVentaEnCaja.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtPanelVentaEnCaja.setText("Panel de Venta en Caja");
        add(txtPanelVentaEnCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras (1).png"))); // NOI18N
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        btnReiniciarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/deshacer (1).png"))); // NOI18N
        btnReiniciarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReiniciarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReiniciarVentaMouseClicked(evt);
            }
        });
        add(btnReiniciarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 70, -1, -1));

        btnAtajos.setBackground(new java.awt.Color(44, 44, 44));
        btnAtajos.setRoundBottomLeft(15);
        btnAtajos.setRoundBottomRight(15);
        btnAtajos.setRoundTopLeft(15);
        btnAtajos.setRoundTopRight(15);
        btnAtajos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConsultarAtajos.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        btnConsultarAtajos.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarAtajos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConsultarAtajos.setText("Consultar Atajos");
        btnConsultarAtajos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultarAtajos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarAtajosMouseClicked(evt);
            }
        });
        btnAtajos.add(btnConsultarAtajos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        add(btnAtajos, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, 220, 50));

        txtBusquedaNombre1.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        txtBusquedaNombre1.setText("Busqueda Nombre:");
        add(txtBusquedaNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 210, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void inputCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputCodigoFocusGained
        if (inputCodigo.getText().equals("Codigo")) {
            inputCodigo.setText("");
        }
    }//GEN-LAST:event_inputCodigoFocusGained

    private void inputCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputCodigoFocusLost
        if (inputCodigo.getText().trim().isEmpty()) {
            inputCodigo.setText("Codigo");
        }
    }//GEN-LAST:event_inputCodigoFocusLost

    private void inputNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombreFocusGained
        if (inputNombre.getText().equals("Nombre Producto")) {
            inputNombre.setText("");
        }
    }//GEN-LAST:event_inputNombreFocusGained

    private void inputNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombreFocusLost
        if (inputNombre.getText().trim().isEmpty()) {
            inputNombre.setText("Nombre Producto");
        }
    }//GEN-LAST:event_inputNombreFocusLost

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        app.mostrarMenuOpciones();
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void btnTxtTarjetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTxtTarjetaMouseClicked

        try {
            // setear la venta con los totales y los productosVenta

            if (app.obtenerVenta() != null && app.obtenerVenta().getPago() != null) {
                app.mostrarVentaYaPagada();
            } else {
                VentaDTO venta = new VentaDTO();
                venta.setEmpleado(app.cargarEmpleado());
                venta.setFechaHora(LocalDateTime.now());
                venta.setIva(app.getIvaVenta());
                venta.setTotal(app.getTotalVenta());
                venta.setSubtotal(app.getSubtotalVenta());
                venta.setListadoProductosVenta(listadoProductosVenta);

                app.setearVenta(venta);
                app.mostrarFormularioTarjeta();
            }
        } catch (NegocioException ex) {
            Logger.getLogger(RegistrarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTxtTarjetaMouseClicked

    private void btnTxtEfectivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTxtEfectivoMouseClicked

        try {
            // setear la venta con los totales y los productosVenta

            if (app.obtenerVenta() != null && app.obtenerVenta().getPago() != null) {
                app.mostrarVentaYaPagada();
            } else {
                VentaDTO venta = new VentaDTO();
                venta.setEmpleado(app.cargarEmpleado());
                venta.setFechaHora(LocalDateTime.now());
                venta.setIva(app.getIvaVenta());
                venta.setTotal(app.getTotalVenta());
                venta.setSubtotal(app.getSubtotalVenta());
                venta.setListadoProductosVenta(listadoProductosVenta);

                app.setearVenta(venta);
                app.mostrarFormularioEfectivo();
            }
        } catch (NegocioException ex) {
            Logger.getLogger(RegistrarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnTxtEfectivoMouseClicked

    private void btnReiniciarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReiniciarVentaMouseClicked
        int opcion = app.mostrarPreguntaReiniciarVenta();
        if (opcion == JOptionPane.YES_OPTION) {
            reiniciarVenta();
        }
    }//GEN-LAST:event_btnReiniciarVentaMouseClicked

    private void inputCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCodigoKeyReleased
        String textoBusqueda = inputCodigo.getText().trim();
        try {
            buscarProducto(textoBusqueda);
        } catch (NegocioException ex) {
            Logger.getLogger(RegistrarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_inputCodigoKeyReleased

    private void inputNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombreKeyReleased
        String textoBusqueda = inputNombre.getText().trim();
        try {
            buscarProducto(textoBusqueda);
        } catch (NegocioException ex) {
            Logger.getLogger(RegistrarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_inputNombreKeyReleased

    private void inputCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCodigoKeyTyped
        char c = evt.getKeyChar();
        // Solo permite números (0-9) y retroceso
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume(); // Ignora la entrada si no es válida
        }
    }//GEN-LAST:event_inputCodigoKeyTyped

    private void inputNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombreKeyTyped
        char c = evt.getKeyChar();
        // Permitir solo letras, espacios y retroceso
        if (!Character.isLetter(c) && c != ' ' && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume(); // Ignorar entrada si no es válida
        }
    }//GEN-LAST:event_inputNombreKeyTyped

    private void listadoGraficoProductosCargadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoGraficoProductosCargadosMouseClicked
        if (evt.getClickCount() == 2) { // Doble clic
            agregarProductoVenta(); // Llama al método al doble clic
        }
    }//GEN-LAST:event_listadoGraficoProductosCargadosMouseClicked

    private void listadoGraficoProductosCargadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listadoGraficoProductosCargadosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { // Si presiona Enter
            agregarProductoVenta(); // Llama al método
        }
    }//GEN-LAST:event_listadoGraficoProductosCargadosKeyPressed

    private void btnConsultarAtajosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarAtajosMouseClicked
        abrirDialogoAtajos();
    }//GEN-LAST:event_btnConsultarAtajosMouseClicked

    private void tablaProductosVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosVentaMouseClicked
        if (evt.getClickCount() == 2) { // Doble clic
            int respuesta = app.mostrarPreguntaEliminarProducto();
            if (respuesta == JOptionPane.YES_OPTION) { // tambien mandar a abrir jOptionPanes desde aplicacion.
                eliminarProducto(); // Llama al método al doble clic --- aqui necesito quitar el producto de la lista local
                calcularTotales();
            } else {
                // Limpiar la selección
                tablaProductosVenta.getSelectionModel().clearSelection();
            }
        }
    }//GEN-LAST:event_tablaProductosVentaMouseClicked

    private void btnFinalizarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarVentaMouseClicked
        try {
            finalizarVenta();
        } catch (NegocioException ex) {
            Logger.getLogger(RegistrarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFinalizarVentaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.PanelRound btnAtajos;
    private javax.swing.JLabel btnAtras;
    private javax.swing.JLabel btnConsultarAtajos;
    private GUI.PanelRound btnEfectivo;
    private GUI.PanelRound btnFinalizarVenta;
    private javax.swing.JLabel btnReiniciarVenta;
    private GUI.PanelRound btnTarjeta;
    private javax.swing.JLabel btnTxtEfectivo;
    private javax.swing.JLabel btnTxtFinalizarVenta;
    private javax.swing.JLabel btnTxtTarjeta;
    private javax.swing.JTextField inputCodigo;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JScrollPane listaProductos;
    private javax.swing.JList<String> listadoGraficoProductosCargados;
    private GUI.PanelRound pnlTotal;
    private javax.swing.JTable tablaProductosVenta;
    private javax.swing.JScrollPane tblProductosVenta;
    private javax.swing.JLabel txtBusquedaCodigo;
    private javax.swing.JLabel txtBusquedaNombre;
    private javax.swing.JLabel txtBusquedaNombre1;
    private javax.swing.JLabel txtCajero;
    private javax.swing.JLabel txtIva;
    private javax.swing.JLabel txtPanelVentaEnCaja;
    private javax.swing.JLabel txtSubtotal;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables

    //Metodos Auxiliares para presentacion
    public void ajustarTamañoColumnasPreferidos() {
        tablaProductosVenta.getColumnModel().getColumn(0).setPreferredWidth(80);  // Código
        tablaProductosVenta.getColumnModel().getColumn(1).setPreferredWidth(300); // Descripción del artículo
        tablaProductosVenta.getColumnModel().getColumn(2).setPreferredWidth(60);  // Cantidad
        tablaProductosVenta.getColumnModel().getColumn(3).setPreferredWidth(80);  // Precio
        tablaProductosVenta.getColumnModel().getColumn(4).setPreferredWidth(80);  // Importe
    }

    public void cargarEmpleado() throws NegocioException {
        EmpleadoCargadoDTO empleadoCargado = app.cargarEmpleado();
        txtCajero.setText("Cajero:  " + empleadoCargado.getNombre());
    }

    public void cargarProductos() throws NegocioException {
        List<ProductoCargadoDTO> nuevosProductos = app.cargarProductos(); // Siempre nueva lista

        listadoProductosCargados = nuevosProductos; // Reemplaza, no acumula

        DefaultListModel<String> modelo = new DefaultListModel<>();
        for (ProductoCargadoDTO p : nuevosProductos) {
            modelo.addElement(p.getCodigo() + " " + p.getNombre() + " " + p.getDescripcion() + "  $" + p.getPrecio());
        }

        listadoGraficoProductosCargados.setModel(modelo); // Asigna un modelo nuevo limpio
    }

    public void reiniciarVenta() { // verificar correcto funcionamiento -----
        DefaultTableModel modelo = (DefaultTableModel) tablaProductosVenta.getModel();
        modelo.setRowCount(0); // Elimina todas las filas
        listadoProductosCargados.clear(); // se elimina de la lista local cargada
        listadoProductosVenta.clear();
        //resetear totales con la tabla vacia
        calcularTotales();
        app.setearVenta(null);

        inputCodigo.setText("");
        inputNombre.setText("");
    }

    public void inicializarValoresDefault() throws NegocioException {
        cargarEmpleado();
        cargarProductos();
        ajustarTamañoColumnasPreferidos();
        crearAtajos();

    }

    private void buscarProducto(String textoBusqueda) throws NegocioException {
        DefaultListModel<String> modeloFiltrado = new DefaultListModel<>();

        if (textoBusqueda.trim().isEmpty()) {
            cargarProductos();
            return;
        }

        for (ProductoCargadoDTO p : listadoProductosCargados) {
            String infoProducto = p.getCodigo() + " " + p.getNombre() + " " + p.getDescripcion() + " $" + p.getPrecio();
            // Convertir todo a minúsculas para búsqueda flexible
            String productoNormalizado = infoProducto.toLowerCase().replaceAll("\\s+", "");
            String textoNormalizado = textoBusqueda.toLowerCase().replaceAll("\\s+", "");
            if (productoNormalizado.contains(textoNormalizado)) {
                modeloFiltrado.addElement(infoProducto);
            }
        }

        if (modeloFiltrado.isEmpty()) {
            modeloFiltrado.addElement("No se encontraron coincidencias.");
        }
        listadoGraficoProductosCargados.setModel(modeloFiltrado);
    }

    public void agregarProductoVenta() {
        // Obtener el String seleccionado de la listaGraficaDeProductosCargados
        String infoProducto = listadoGraficoProductosCargados.getSelectedValue();

        if (infoProducto != null && !infoProducto.isEmpty()) {
            // Convertir el String a ProductoCargadoDTO
            ProductoCargadoDTO productoCargado = convertirStringAProducto(infoProducto);

            if (productoCargado != null) {
                try {
                    // Obtener la cantidad del producto
                    String respuesta = app.mostrarIngresarCantidad();
                    if (respuesta == null) {
                        return;
                    }
                    double cantidad = Double.parseDouble(respuesta);
                    // Validar que la cantidad sea mayor que 0
                    if (cantidad <= 0) {
                        app.mostrarErrorCantidadMayor0();
                        return;
                    }

                    // Agregar el producto convertido a la venta
                    ProductoVentaDTO productoVenta = app.agregarProducto(productoCargado, cantidad);

                    // Obtener el modelo de la tabla
                    DefaultTableModel modelo = obtenerTablaProductosVenta();

                    // Crear un arreglo con los valores del producto para agregarlo a la tabla
                    Object[] fila = {
                        productoVenta.getProducto().getCodigo(),
                        productoVenta.getProducto().getNombre() + " " + productoVenta.getProducto().getDescripcion(),
                        productoVenta.getCantidad(),
                        productoVenta.getPrecioUnitario(),
                        productoVenta.getImporte()
                    };
                    modelo.addRow(fila);

                    // llamadaMetodo actualizarTotal
                    calcularTotales();

                    listadoProductosVenta.add(productoVenta); // talvez podria ser en vez de un add un setear que le hable a la app------------------------ yo creo que si sera remplazado para alla.
                } catch (NumberFormatException e) {
                    app.mostrarErrorValorNumericoValido();
                }
            } else {
                app.mostrarErrorConvertirProducto();
            }
        } else {
            app.mostrarErrorSeleccionaProductoValido();
        }
    }

    public ProductoCargadoDTO convertirStringAProducto(String infoProducto) {
        try {
            if (infoProducto == null || infoProducto.isBlank()) {
                return null;
            }

            String[] partes = infoProducto.trim().split(" ");
            if (partes.length < 3) {
                return null;
            }

            // Validar que el código sea numérico
            if (partes[0].equalsIgnoreCase("null") || !partes[0].matches("\\d+")) {
                return null;
            }

            int codigo = Integer.parseInt(partes[0]);

            // Armar el nombre hasta encontrar el precio
            StringBuilder nombreBuilder = new StringBuilder();
            int i = 1;
            while (i < partes.length && !partes[i].startsWith("$")) {
                nombreBuilder.append(partes[i]).append(" ");
                i++;
            }

            String nombreCompleto = nombreBuilder.toString().trim();

            // Validar que haya un precio al final
            if (!partes[partes.length - 1].startsWith("$")) {
                return null;
            }

            String precioTexto = partes[partes.length - 1].replace("$", "");
            double precio = Double.parseDouble(precioTexto);

            return new ProductoCargadoDTO(codigo, nombreCompleto, "Descripción", precio);

        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public void calcularTotales() {
        List<NuevoProductoVentaDTO> productosVenta = new ArrayList<>();

        DefaultTableModel modelo = obtenerTablaProductosVenta();

        // Recorrer todas las filas de la tabla
        for (int i = 0; i < modelo.getRowCount(); i++) {
            int codigo = (int) modelo.getValueAt(i, 0); // Columna 0 -> Código
            String nombreDescripcion = (String) modelo.getValueAt(i, 1); // Columna 1 -> Nombre + Descripción
            double cantidad = (double) modelo.getValueAt(i, 2); // Columna 2 -> Cantidad
            double precioUnitario = (double) modelo.getValueAt(i, 3); // Columna 3 -> Precio Unitario
            double importe = (double) modelo.getValueAt(i, 4); // Columna 4 -> Importe

            // Crear el objeto ProductoCargadoDTO si es necesario
            ProductoCargadoDTO producto = new ProductoCargadoDTO(codigo, nombreDescripcion, "", precioUnitario);

            // Crear el objeto NuevoProductoVentaDTO
            NuevoProductoVentaDTO productoVenta = new NuevoProductoVentaDTO(producto, cantidad, precioUnitario, importe);

            // Agregarlo a la lista
            productosVenta.add(productoVenta);
        }
        double subtotalCalculado = app.calcularSubTotal(productosVenta);
        double iva = app.calcularIVA(subtotalCalculado);
        double total = app.calcularTotal(subtotalCalculado, iva); // en este metodo es donde mando el total guardado al subsistema pasando por la aplicacion.

        //ENVIAR LOS TOTALES A EL REALIZAR VENTA
        app.setTotalTemporal(total);
        app.setIvaVenta(iva);
        app.setSubtotalVenta(subtotalCalculado);

        String textoTotal = "Total: $" + String.format("%.2f", total);
        txtTotal.setText(textoTotal);
        ajustarTamanoTexto(txtTotal, textoTotal);

        String textoSubtotal = "Subtotal: $" + String.format("%.2f", subtotalCalculado);
        txtSubtotal.setText(textoSubtotal);
        ajustarTamanoTexto(txtSubtotal, textoSubtotal);

        String textoIva = "IVA(16%): $" + String.format("%.2f", iva);
        txtIva.setText(textoIva);
        ajustarTamanoTexto(txtIva, textoIva);
    }

    public void ajustarTamanoTexto(JLabel label, String texto) {
        Font fuenteOriginal = label.getFont();
        int anchoLabel = label.getWidth();

        int tamanoFuente = fuenteOriginal.getSize();
        FontMetrics fm = label.getFontMetrics(fuenteOriginal);

        while (fm.stringWidth(texto) > anchoLabel && tamanoFuente > 10) {
            tamanoFuente--;
            fuenteOriginal = fuenteOriginal.deriveFont((float) tamanoFuente);
            fm = label.getFontMetrics(fuenteOriginal);
        }
        label.setFont(fuenteOriginal);
        label.setText(texto);
    }

    public void crearAtajos() {
        // Crear un mapa para asociar teclas con métodos
        Map<KeyStroke, Runnable> acciones = Map.of(
                KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0), app::mostrarFormularioEfectivo,
                KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0), app::mostrarFormularioTarjeta,
                KeyStroke.getKeyStroke(KeyEvent.VK_F8, 0), () -> inputCodigo.requestFocus(), // Asignar foco al inputCodigo
                KeyStroke.getKeyStroke(KeyEvent.VK_F9, 0), () -> inputNombre.requestFocus(), // Asignar foco al inputNombre
                KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), app::mostrarTicketPDF,
                KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0), this::reiniciarVenta,
                KeyStroke.getKeyStroke(KeyEvent.VK_A, InputEvent.CTRL_DOWN_MASK), this::abrirDialogoAtajos
        );

        // Obtener InputMap y ActionMap del JPanel
        InputMap inputMap = this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap actionMap = this.getActionMap();

        // Recorrer el mapa para asignar cada atajo
        for (Map.Entry<KeyStroke, Runnable> entrada : acciones.entrySet()) {
            String nombreAccion = "accion" + entrada.getKey(); // Nombre dinámico para cada acción

            inputMap.put(entrada.getKey(), nombreAccion);
            actionMap.put(nombreAccion, new AbstractAction() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    entrada.getValue().run(); // Ejecuta el método asociado
                }
            });
        }
    }

    public void abrirDialogoAtajos() {
        JDialog dialogo = new JDialog((JFrame) SwingUtilities.getWindowAncestor(this), "Atajos del Sistema", true);
        dialogo.setSize(400, 350);
        dialogo.setLayout(new BorderLayout());
        dialogo.setLocationRelativeTo(this);

        JTextArea txtAtajos = new JTextArea(
                """
        F1   - Opción Pago Efectivo
        F2   - Opción Pago Tarjeta
        F8   - Buscar por Código
        F9   - Buscar por Nombre
        F10  - Finalizar Venta
        F12  - Reiniciar Venta
        
        Ctrl + A  Mostrar Atajos
        """
        );
        txtAtajos.setFont(new Font("Monospaced", Font.PLAIN, 20));
        txtAtajos.setEditable(false);
        txtAtajos.setMargin(new Insets(10, 10, 10, 10)); // Márgenes
        dialogo.add(new JScrollPane(txtAtajos), BorderLayout.CENTER);

        JButton btnCerrar = new JButton("Cerrar");
        btnCerrar.addActionListener(e -> dialogo.dispose()); // Cerrar el diálogo

        // Agregar el botón al diálogo
        JPanel panelBoton = new JPanel();
        panelBoton.add(btnCerrar);
        dialogo.add(panelBoton, BorderLayout.SOUTH);

        dialogo.setVisible(true);
    }

    // no debe ir la logica 
    /*
    public VentaDTO guardarVenta() {
        LocalDate fecha = LocalDate.now();
        EmpleadoCargadoDTO empleadoCargado = app.cargarEmpleado();
        VentaDTO ventaNueva = new VentaDTO(empleadoCargado, fecha, listadoProductosVenta);

        app.setearVenta(ventaNueva);

        return ventaNueva;
    }*/
    public void eliminarProducto() {
        DefaultTableModel modelo = (DefaultTableModel) tablaProductosVenta.getModel();

        int filaAEliminar = tablaProductosVenta.getSelectedRow();
        if (filaAEliminar != -1) {
            // Eliminar la fila del modelo de la tabla
            modelo.removeRow(filaAEliminar);

            // Limpiar la selección
            tablaProductosVenta.getSelectionModel().clearSelection();
            listadoProductosVenta.remove(filaAEliminar);
        }
    }

    public DefaultTableModel obtenerTablaProductosVenta() {
        return (DefaultTableModel) tablaProductosVenta.getModel();
    }

    public void finalizarVenta() throws NegocioException {
        int confirmar = app.mostrarPreguntaFinalizarVenta();
        EmpleadoCargadoDTO empleado = app.cargarEmpleado();
        VentaDTO ventaRealizada = app.obtenerVenta();

        // Validar si el empleado se cargó correctamente
        if (empleado == null) {
            app.mostrarErrorEmpleadoNoCargado();
            return;
        }

        // Validar si la lista de productos es válida
        if (listadoProductosVenta == null || listadoProductosVenta.isEmpty()) {
            app.mostrarErrorVentaSinProductos();
            return;
        }

        // Validar que la venta haya sido pagada
        if (ventaRealizada == null || ventaRealizada.getPago() == null) {
            System.out.println("La venta aun no ha sido pagada.");
            app.mostrarVentaCancelada();
            return;
        }

        String estadoPago = ventaRealizada.getPago().getEstado();

        if (!"Pagado".equalsIgnoreCase(estadoPago)) {
            System.out.println("La venta no ha sido pagada");
            app.mostrarVentaCancelada();
            return;
        }

        // Si se confirma finalizar la venta
        // Si se confirma finalizar la venta
        if (confirmar == JOptionPane.YES_OPTION) {
            
            try {
                VentaDTO venta = app.registrarVenta(ventaRealizada);
                app.setearVenta(venta);
                app.mostrarTicketPDF();
            } catch (VentaException ex) {
                Logger.getLogger(RegistrarVenta.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            app.mostrarVentaCancelada();
        }
    }

}
