/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ModuloGastos;

/**
 *
 * @author Admin
 */
public class FormularioAgregarProveedor extends javax.swing.JPanel {

    /**
     * Creates new form FormularioAgregarProveedor
     */
    public FormularioAgregarProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        agregarProveedorPanelRound = new GUI.PanelRound();
        btnAgregarProveedor = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Product Sans Infanity", 0, 60)); // NOI18N
        jLabel1.setText("Agregar Proveedor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 520, -1));

        jLabel2.setFont(new java.awt.Font("Product Sans Infanity", 0, 36)); // NOI18N
        jLabel2.setText("Nombre del proveedor");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 310, 40));

        agregarProveedorPanelRound.setBackground(new java.awt.Color(44, 44, 44));
        agregarProveedorPanelRound.setRoundBottomLeft(10);
        agregarProveedorPanelRound.setRoundBottomRight(10);
        agregarProveedorPanelRound.setRoundTopLeft(10);
        agregarProveedorPanelRound.setRoundTopRight(10);
        agregarProveedorPanelRound.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarProveedor.setFont(new java.awt.Font("Product Sans Infanity", 0, 36)); // NOI18N
        btnAgregarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregarProveedor.setText("Agregar");
        agregarProveedorPanelRound.add(btnAgregarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 80));

        add(agregarProveedorPanelRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 350, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.PanelRound agregarProveedorPanelRound;
    private javax.swing.JLabel btnAgregarProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
