/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ModuloGastos;

import DTOs.CrearGastoDTO;
import DTOs.CrearProveedorDTO;
import DTOs.ProveedorDTO;
import Exception.GastoException;
import GUI.Aplicacion;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class FormularioEditarGasto extends javax.swing.JPanel {

    Aplicacion app;

    /**
     * Creates new form FormularioRegistrarGasto
     */
    public FormularioEditarGasto(Aplicacion app) {
        this.app = app;
        initComponents();
        cargarProveedores();
        inicializarCampos();

        //inicializar campos
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputConcepto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboMetodoPago = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputMontoGasto = new javax.swing.JTextField();
        panelRound2 = new GUI.PanelRound();
        btnEliminar = new javax.swing.JLabel();
        btnAtras = new javax.swing.JLabel();
        inputFecha = new com.toedter.calendar.JDateChooser();
        panelRound3 = new GUI.PanelRound();
        btnGuardarEditado = new javax.swing.JLabel();
        comboProveedor = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(228, 233, 236));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Product Sans Infanity", 0, 60)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Gasto");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 450, -1));

        inputConcepto.setAlignmentY(0.0F);
        add(inputConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 1010, 60));

        jLabel3.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        jLabel3.setText("Concepto");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        comboMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta" }));
        add(comboMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 100, 30));

        jLabel5.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        jLabel5.setText("Metodo de pago utilizado");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 20));

        jLabel6.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        jLabel6.setText("Fecha del gasto");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, 20));

        jLabel7.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        jLabel7.setText("Monto del gasto");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, 20));

        jLabel8.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        jLabel8.setText("Proveedor");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, 20));

        inputMontoGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMontoGastoActionPerformed(evt);
            }
        });
        add(inputMontoGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 200, 40));

        panelRound2.setBackground(new java.awt.Color(255, 0, 0));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setFont(new java.awt.Font("Product Sans Infanity", 0, 48)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminar.setText("Eliminar");
        panelRound2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 90));

        add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 390, 90));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icnAtras.png"))); // NOI18N
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        add(inputFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 150, 30));

        panelRound3.setBackground(new java.awt.Color(44, 44, 44));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarEditado.setFont(new java.awt.Font("Product Sans Infanity", 0, 48)); // NOI18N
        btnGuardarEditado.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarEditado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardarEditado.setText("Guardar");
        panelRound3.add(btnGuardarEditado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 90));

        add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 540, 390, 90));

        comboProveedor.setModel(new javax.swing.DefaultComboBoxModel<>());
        add(comboProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 200, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void inputMontoGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMontoGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMontoGastoActionPerformed

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        // TODO add your handling code here:
        app.mostrarPantallaHistorialGastos();
    }//GEN-LAST:event_btnAtrasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAtras;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnGuardarEditado;
    private javax.swing.JComboBox<String> comboMetodoPago;
    private javax.swing.JComboBox<CrearProveedorDTO> comboProveedor;
    private javax.swing.JTextField inputConcepto;
    private com.toedter.calendar.JDateChooser inputFecha;
    private javax.swing.JTextField inputMontoGasto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private GUI.PanelRound panelRound2;
    private GUI.PanelRound panelRound3;
    // End of variables declaration//GEN-END:variables

    public void inicializarCampos() {
        
        CrearGastoDTO gasto = app.getCrearGastoDTO();


        // Concepto
        inputConcepto.setText(gasto.getConcepto());

        // Método de pago
        comboMetodoPago.setSelectedItem(gasto.getMetodoPago());

        // Fecha
        LocalDate fechaLocal = gasto.getFechaGasto();
        Date fechaDate = java.sql.Date.valueOf(fechaLocal);
        inputFecha.setDate(fechaDate);

        // Monto
        inputMontoGasto.setText(gasto.getMontoGasto().toString());


    }
    
    public void cargarProveedores() {
        try {
            List<ProveedorDTO> proveedores = app.consultarProveedores();
            CrearGastoDTO gasto = app.getCrearGastoDTO();
            
            comboProveedor.addItem(gasto.getProveedor());
            for (ProveedorDTO proveedor : proveedores) {
                CrearProveedorDTO cpdto = new CrearProveedorDTO(proveedor.getNombre());
                if(proveedor.getNombre().equals(gasto.getProveedor().getNombre())){
                    
                }else{
                   comboProveedor.addItem(cpdto); 
                }

            }
        } catch (GastoException ex) {
            Logger.getLogger(FormularioRegistrarGasto.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }


}
