/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ModuloGastos;

import GUI.Aplicacion;

/**
 *
 * @author Admin
 */
public class MenuGastos extends javax.swing.JPanel {

    Aplicacion app;
    /**
     * Creates new form MenuGas
     */
    public MenuGastos(Aplicacion app) {
        this.app = app;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        regisrarGastoPanelRound = new GUI.PanelRound();
        btnRegistrarGasto = new javax.swing.JLabel();
        historialGastosPanelRound = new GUI.PanelRound();
        btnHistorialGastos = new javax.swing.JLabel();
        agregarProveedorPanelRound = new GUI.PanelRound();
        btnAgregarProveedor = new javax.swing.JLabel();
        btnAtras = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Product Sans Infanity", 0, 60)); // NOI18N
        jLabel1.setText("Menu de Gastos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 450, -1));

        regisrarGastoPanelRound.setBackground(new java.awt.Color(44, 44, 44));
        regisrarGastoPanelRound.setRoundBottomLeft(10);
        regisrarGastoPanelRound.setRoundBottomRight(10);
        regisrarGastoPanelRound.setRoundTopLeft(10);
        regisrarGastoPanelRound.setRoundTopRight(10);
        regisrarGastoPanelRound.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarGasto.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        btnRegistrarGasto.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarGasto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrarGasto.setText("Registrar un nuevo Gasto");
        btnRegistrarGasto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarGasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarGastoMouseClicked(evt);
            }
        });
        regisrarGastoPanelRound.add(btnRegistrarGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 320, 80));

        add(regisrarGastoPanelRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 340, 80));

        historialGastosPanelRound.setBackground(new java.awt.Color(44, 44, 44));
        historialGastosPanelRound.setRoundBottomLeft(10);
        historialGastosPanelRound.setRoundBottomRight(10);
        historialGastosPanelRound.setRoundTopLeft(10);
        historialGastosPanelRound.setRoundTopRight(10);
        historialGastosPanelRound.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHistorialGastos.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        btnHistorialGastos.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialGastos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHistorialGastos.setText("Historial de Gastos");
        btnHistorialGastos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistorialGastosMouseClicked(evt);
            }
        });
        historialGastosPanelRound.add(btnHistorialGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 80));

        add(historialGastosPanelRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 340, 80));

        agregarProveedorPanelRound.setBackground(new java.awt.Color(44, 44, 44));
        agregarProveedorPanelRound.setRoundBottomLeft(10);
        agregarProveedorPanelRound.setRoundBottomRight(10);
        agregarProveedorPanelRound.setRoundTopLeft(10);
        agregarProveedorPanelRound.setRoundTopRight(10);
        agregarProveedorPanelRound.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarProveedor.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        btnAgregarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregarProveedor.setText("Agregar Proveedor");
        btnAgregarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarProveedorMouseClicked(evt);
            }
        });
        agregarProveedorPanelRound.add(btnAgregarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 80));

        add(agregarProveedorPanelRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 320, 80));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras (1).png"))); // NOI18N
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistorialGastosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialGastosMouseClicked
        // TODO add your handling code here:
        app.mostrarPantallaHistorialGastos();
    }//GEN-LAST:event_btnHistorialGastosMouseClicked

    private void btnRegistrarGastoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarGastoMouseClicked
        // TODO add your handling code here:
        app.mostrarRegistrarGasto();
    }//GEN-LAST:event_btnRegistrarGastoMouseClicked

    private void btnAgregarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProveedorMouseClicked
        // TODO add your handling code here:
        app.mostrarAgregarProveedor();
    }//GEN-LAST:event_btnAgregarProveedorMouseClicked

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        app.mostrarMenuOpciones();
    }//GEN-LAST:event_btnAtrasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.PanelRound agregarProveedorPanelRound;
    private javax.swing.JLabel btnAgregarProveedor;
    private javax.swing.JLabel btnAtras;
    private javax.swing.JLabel btnHistorialGastos;
    private javax.swing.JLabel btnRegistrarGasto;
    private GUI.PanelRound historialGastosPanelRound;
    private javax.swing.JLabel jLabel1;
    private GUI.PanelRound regisrarGastoPanelRound;
    // End of variables declaration//GEN-END:variables
}
