/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ModuloGastos;

import DTOs.CrearGastoDTO;
import DTOs.CrearProveedorDTO;
import DTOs.GastoDTO;
import DTOs.ProveedorDTO;
import Exception.GastoException;
import GUI.Aplicacion;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class TablaHistorialGastos extends javax.swing.JPanel {

    Aplicacion app;
      List<GastoDTO> gastosLista;

    /**
     * Creates new form tableHistorialGastos
     */
    public TablaHistorialGastos(Aplicacion app) {
        this.app = app;
        initComponents();
        llenarTablaInicial();

        //listeners para filtros
        jComboBox1.addActionListener(e -> aplicarFiltros());
        jComboBox2.addActionListener(e -> aplicarFiltros());

        jDateChooser1.addPropertyChangeListener("date", evt -> aplicarFiltros());
        jDateChooser2.addPropertyChangeListener("date", evt -> aplicarFiltros());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHisotrialGastos = new javax.swing.JTable();
        btnGenerarReporte = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        bntAtras = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Product Sans Infanity", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Historial Gastos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 450, -1));

        tablaHisotrialGastos.setBackground(new java.awt.Color(255, 255, 255));
        tablaHisotrialGastos.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        tablaHisotrialGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Categoria", "Folio", "Concepto", "Metodo de pago utilizado", "Fecha del gasto", "Monto del gasto", "Proveedor", ""
            }
        ));
        tablaHisotrialGastos.setFocusable(false);
        tablaHisotrialGastos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tablaHisotrialGastos.setRowHeight(30);
        tablaHisotrialGastos.getTableHeader().setResizingAllowed(false);
        tablaHisotrialGastos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaHisotrialGastos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1150, 550));

        btnGenerarReporte.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        btnGenerarReporte.setText(" Generar Reporte.pdf");
        btnGenerarReporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGenerarReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerarReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarReporteMouseClicked(evt);
            }
        });
        add(btnGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, 180, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 100, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 100, -1));

        bntAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icnAtras.png"))); // NOI18N
        bntAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntAtrasMouseClicked(evt);
            }
        });
        add(bntAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Filtros");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel4.setText("Metodo de pago");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Insumos", "Materias Primas", "Mantenimiento/Servicios" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 140, -1));

        jLabel5.setText("Categoria");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, 20));

        jLabel6.setText("FechaInicio");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));
        add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 100, -1));

        jLabel7.setText("FechaFin");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bntAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntAtrasMouseClicked
        // TODO add your handling code here:
        app.mostrarPantallaMenuGastos();
    }//GEN-LAST:event_bntAtrasMouseClicked

    private void btnGenerarReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReporteMouseClicked

       app.generarPDFGasto(gastosLista);

    }//GEN-LAST:event_btnGenerarReporteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bntAtras;
    private javax.swing.JLabel btnGenerarReporte;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaHisotrialGastos;
    // End of variables declaration//GEN-END:variables

    public void llenarTablaInicial() {
        try {
            List<GastoDTO> gastos = app.consultarGastos();
            gastosLista = gastos;
            String[] columnas = {
                "Categoria", "Folio", "Concepto", "Metodo de pago utilizado",
                "Fecha del gasto", "Monto del gasto", "Proveedor", "Editar"
            };

            javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // ninguna celda editable
                }
            };

            for (GastoDTO gasto : gastos) {
                Object[] fila = new Object[]{
                    gasto.getCategoria(),
                    gasto.getFolio(),
                    gasto.getConcepto(),
                    gasto.getMetodoPago(),
                    gasto.getFechaGasto().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                    gasto.getMontoGasto(),
                    gasto.getProveedor() != null ? gasto.getProveedor().getNombre() : "Sin proveedor",
                    "<html><span style='color:blue; text-decoration:underline;'>Editar</span></html>"
                };
                modelo.addRow(fila);
            }

            tablaHisotrialGastos.setModel(modelo);

            tablaHisotrialGastos.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent e) {
                    int fila = tablaHisotrialGastos.rowAtPoint(e.getPoint());
                    int columna = tablaHisotrialGastos.columnAtPoint(e.getPoint());

                    if (columna == 7 && fila != -1) { //columna "Editar"

                        //Categoria
                        Object categoria = tablaHisotrialGastos.getValueAt(fila, 0);
                        String categoriaString = String.valueOf(categoria);

                        //Folio
                        Object folio = tablaHisotrialGastos.getValueAt(fila, 1);
                        String folioString = String.valueOf(folio);

                        //Concepto
                        Object concepto = tablaHisotrialGastos.getValueAt(fila, 2);
                        String conceptoString = String.valueOf(concepto);

                        //Metodo de pago
                        Object metodoPago = tablaHisotrialGastos.getValueAt(fila, 3);
                        String metodoPagoString = String.valueOf(metodoPago);

                        //Fecha del gasto
                        String fechaString = String.valueOf(tablaHisotrialGastos.getValueAt(fila, 4));
                        LocalDate fechaGasto = LocalDate.parse(fechaString, DateTimeFormatter.ofPattern("dd/MM/yyyy"));

                        //Monto
                        String montoString = String.valueOf(tablaHisotrialGastos.getValueAt(fila, 5));
                        double montoGasto = Double.parseDouble(montoString);
                        //Proveedor
                        String nombreProveedor = String.valueOf(tablaHisotrialGastos.getValueAt(fila, 6));
                        CrearProveedorDTO proveedor = new CrearProveedorDTO();
                        proveedor.setNombre(nombreProveedor);

                        CrearGastoDTO gastoEditable = new CrearGastoDTO();
                        gastoEditable.setCategoria(categoriaString);
                        gastoEditable.setFolio(folioString);
                        gastoEditable.setConcepto(conceptoString);
                        gastoEditable.setMetodoPago(metodoPagoString);
                        gastoEditable.setFechaGasto(fechaGasto);
                        gastoEditable.setMontoGasto(montoGasto);
                        gastoEditable.setProveedor(proveedor);

                        app.setCrearGastoDTO(gastoEditable);

                        app.mostrarPantallaEditarGasto();
                    }
                }
            });

        } catch (GastoException ex) {
            Logger.getLogger(TablaHistorialGastos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void aplicarFiltros() {
        try {
            CrearGastoDTO filtro = new CrearGastoDTO();//DTO para filtros

            String metodoPago = (String) jComboBox1.getSelectedItem();
            filtro.setMetodoPago(metodoPago);

            String categoria = (String) jComboBox2.getSelectedItem();
            filtro.setCategoria(categoria);

            filtro.setProveedor(null);

            Date fechaInicioDate = jDateChooser2.getDate();
            Date fechaFinDate = jDateChooser1.getDate();

            LocalDate fechaInicio = null;
            LocalDate fechaFin = null;

            ZoneId zonaLocal = ZoneId.systemDefault(); 
            if (fechaInicioDate != null) {
                fechaInicio = fechaInicioDate.toInstant().atZone(zonaLocal).toLocalDate();
            }
            if (fechaFinDate != null) {
                fechaFin = fechaFinDate.toInstant().atZone(zonaLocal).toLocalDate();
            }

            if (fechaInicio == null && fechaFin == null) {
                fechaInicio = null;
                fechaFin = null;
            }


            List<GastoDTO> gastos = app.consultarGastosFiltrados(filtro, fechaInicio, fechaFin);

            actualizarTabla(gastos);
            gastosLista = gastos;
           
        } catch (GastoException ex) {
            Logger.getLogger(TablaHistorialGastos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void actualizarTabla(List<GastoDTO> gastos) {
        String[] columnas = {
            "Categoria", "Folio", "Concepto", "Metodo de pago utilizado",
            "Fecha del gasto", "Monto del gasto", "Proveedor", "Editar"
        };

        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (GastoDTO gasto : gastos) {
            Object[] fila = new Object[]{
                gasto.getCategoria(),
                gasto.getFolio(),
                gasto.getConcepto(),
                gasto.getMetodoPago(),
                gasto.getFechaGasto().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                gasto.getMontoGasto(),
                gasto.getProveedor() != null ? gasto.getProveedor().getNombre() : "Sin proveedor",
                "<html><span style='color:blue; text-decoration:underline;'>Editar</span></html>"
            };
            modelo.addRow(fila);
        }

        tablaHisotrialGastos.setModel(modelo);

        //volver a agregar el listener para editar
        tablaHisotrialGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                int fila = tablaHisotrialGastos.rowAtPoint(e.getPoint());
                int columna = tablaHisotrialGastos.columnAtPoint(e.getPoint());

                if (columna == 7 && fila != -1) { //columna "Editar"

                    //Categoria
                    Object categoria = tablaHisotrialGastos.getValueAt(fila, 0);
                    String categoriaString = String.valueOf(categoria);

                    //Folio
                    Object folio = tablaHisotrialGastos.getValueAt(fila, 1);
                    String folioString = String.valueOf(folio);

                    //Concepto
                    Object concepto = tablaHisotrialGastos.getValueAt(fila, 2);
                    String conceptoString = String.valueOf(concepto);

                    //Metodo de pago
                    Object metodoPago = tablaHisotrialGastos.getValueAt(fila, 3);
                    String metodoPagoString = String.valueOf(metodoPago);

                    //Fecha del gasto
                    String fechaString = String.valueOf(tablaHisotrialGastos.getValueAt(fila, 4));
                    LocalDate fechaGasto = LocalDate.parse(fechaString, DateTimeFormatter.ofPattern("dd/MM/yyyy"));

                    //Monto
                    String montoString = String.valueOf(tablaHisotrialGastos.getValueAt(fila, 5));
                    double montoGasto = Double.parseDouble(montoString);
                    //Proveedor
                    String nombreProveedor = String.valueOf(tablaHisotrialGastos.getValueAt(fila, 6));
                    CrearProveedorDTO proveedor = new CrearProveedorDTO();
                    proveedor.setNombre(nombreProveedor);

                    CrearGastoDTO gastoEditable = new CrearGastoDTO();
                    gastoEditable.setCategoria(categoriaString);
                    gastoEditable.setFolio(folioString);
                    gastoEditable.setConcepto(conceptoString);
                    gastoEditable.setMetodoPago(metodoPagoString);
                    gastoEditable.setFechaGasto(fechaGasto);
                    gastoEditable.setMontoGasto(montoGasto);
                    gastoEditable.setProveedor(proveedor);

                    app.setCrearGastoDTO(gastoEditable);

                    app.mostrarPantallaEditarGasto();
                }
            }
        });
    }

}
